/**
 * The style taxonomy (quality-08): every family root, branch node and leaf
 * as typed data, generated from the plan's taxonomy.json. Each id has one
 * parent; node names and leaf names share one namespace, and every alias
 * names exactly one entry (colliding aliases were dropped at generation).
 * Touchstones are left out on purpose: cards never name artists or works.
 *
 * Row: [id, parent, family, title, aliases, region, eraFrom, eraTo]. A node
 * is any id that is some row's parent; the rest are leaves.
 */

export type StyleFamilyKey =
  | "art"
  | "roots"
  | "rock"
  | "pop"
  | "electronic"
  | "americas"
  | "africa-mena-southasia"
  | "europe-asia-pacific";

export type TaxonomyRow = readonly [
  id: string,
  parent: string | null,
  family: StyleFamilyKey,
  title: string,
  aliases: readonly string[],
  region: readonly string[],
  eraFrom: number | null,
  eraTo: number | null,
];

export const STYLE_FAMILIES: readonly Readonly<{
  key: StyleFamilyKey;
  title: string;
  roots: readonly string[];
}>[] = Object.freeze([
  {
    key: "art",
    title: "Art, experimental, screen and functional",
    roots: ["western-art", "experimental", "screen-stage", "childrens"],
  },
  {
    key: "roots",
    title: "Jazz, blues, soul, gospel, country and North American folk",
    roots: [
      "jazz",
      "blues",
      "rnb-soul",
      "gospel-sacred",
      "country",
      "north-american-folk",
    ],
  },
  { key: "rock", title: "Rock, punk and metal", roots: ["rock-family"] },
  {
    key: "pop",
    title: "Pop, hip hop and breakbeat bass",
    roots: ["pop", "hip-hop", "breakbeat-family"],
  },
  {
    key: "electronic",
    title: "Electronic dance, ambient and experimental electronic",
    roots: ["electronic"],
  },
  {
    key: "americas",
    title: "Caribbean and Latin America",
    roots: ["caribbean", "latin-america"],
  },
  {
    key: "africa-mena-southasia",
    title: "Sub-Saharan Africa, Middle East and North Africa, South Asia",
    roots: ["africa", "mena", "south-asia"],
  },
  {
    key: "europe-asia-pacific",
    title: "European folk, East and Southeast Asia, Oceania",
    roots: ["europe-folk", "east-asia", "southeast-asia", "oceania"],
  },
]);

// prettier-ignore
export const TAXONOMY_ROWS: readonly TaxonomyRow[] = Object.freeze([
  ["western-art", null, "art", "Western art music", [], [], null, null],
  ["early-music", "western-art", "art", "Medieval and Renaissance", ["Early", "Medieval", "Renaissance"], [], null, null],
  ["baroque", "western-art", "art", "Baroque", [], [], null, null],
  ["classical-period", "western-art", "art", "Classical period", ["Classical"], [], null, null],
  ["romantic", "western-art", "art", "Romantic", [], [], null, null],
  ["modern-art", "western-art", "art", "Modernism", ["Modern"], [], null, null],
  ["contemporary-art", "western-art", "art", "Postwar and contemporary", ["Contemporary"], [], null, null],
  ["concert-band", "western-art", "art", "Concert band, brass and military", [], [], null, null],
  ["experimental", null, "art", "Experimental and sound art", ["Avantgarde"], [], null, null],
  ["screen-stage", null, "art", "Film, game and stage", ["Stage & Screen"], [], null, null],
  ["childrens", null, "art", "Children's and functional", [], [], null, null],
  ["jazz", null, "roots", "Jazz", [], [], null, null],
  ["early-jazz", "jazz", "roots", "Early jazz", [], [], null, null],
  ["swing-era", "jazz", "roots", "Swing era", [], [], null, null],
  ["modern-jazz", "jazz", "roots", "Modern jazz", [], [], null, null],
  ["avant-jazz", "jazz", "roots", "Free and avant-garde jazz", [], [], null, null],
  ["jazz-fusion-family", "jazz", "roots", "Fusion and crossover jazz", [], [], null, null],
  ["blues", null, "roots", "Blues", [], [], null, null],
  ["acoustic-blues", "blues", "roots", "Country blues", [], [], null, null],
  ["urban-blues", "blues", "roots", "Urban blues", [], [], null, null],
  ["rnb-soul", null, "roots", "R&B, soul and funk", ["Funk / Soul"], [], null, null],
  ["rhythm-and-blues", "rnb-soul", "roots", "Rhythm and blues", [], [], null, null],
  ["soul", "rnb-soul", "roots", "Soul", [], [], null, null],
  ["modern-rnb", "rnb-soul", "roots", "Modern R&B", [], [], null, null],
  ["funk", "rnb-soul", "roots", "Funk", [], [], null, null],
  ["gospel-sacred", null, "roots", "Gospel and Christian", [], [], null, null],
  ["country", null, "roots", "Country", [], [], null, null],
  ["north-american-folk", null, "roots", "North American folk", [], [], null, null],
  ["rock-family", null, "rock", "Rock, metal and punk", ["Rock"], [], null, null],
  ["early-rock", "rock-family", "rock", "Early rock", [], [], null, null],
  ["classic-rock", "rock-family", "rock", "Classic and hard rock", [], [], null, null],
  ["prog", "rock-family", "rock", "Progressive and art rock", [], [], null, null],
  ["alt-indie", "rock-family", "rock", "Alternative and indie", [], [], null, null],
  ["punk", "rock-family", "rock", "Punk", [], [], null, null],
  ["metal", "rock-family", "rock", "Metal", [], [], null, null],
  ["pop", null, "pop", "Pop", [], [], null, null],
  ["traditional-pop", "pop", "pop", "Traditional and vintage pop", [], [], null, null],
  ["sixties-pop", "pop", "pop", "1960s pop", [], [], null, null],
  ["modern-pop", "pop", "pop", "Modern pop", [], [], null, null],
  ["hip-hop", null, "pop", "Hip hop", [], [], null, null],
  ["old-school", "hip-hop", "pop", "Old school", [], [], null, null],
  ["regional-rap", "hip-hop", "pop", "Regional and classic rap", [], [], null, null],
  ["modern-rap", "hip-hop", "pop", "Modern rap", [], [], null, null],
  ["electronic", null, "electronic", "Electronic", [], [], null, null],
  ["disco-family", "electronic", "electronic", "Disco and its heirs", [], [], null, null],
  ["house", "electronic", "electronic", "House", [], [], null, null],
  ["techno", "electronic", "electronic", "Techno", [], [], null, null],
  ["trance-family", "electronic", "electronic", "Trance styles", [], [], null, null],
  ["hardcore-family", "electronic", "electronic", "Hardcore and hard dance", [], [], null, null],
  ["breakbeat-family", "electronic", "pop", "Breakbeat and bass", [], [], null, null],
  ["downtempo-family", "electronic", "electronic", "Downtempo and chill", [], [], null, null],
  ["ambient-family", "electronic", "electronic", "Ambient and synthesizer music", [], [], null, null],
  ["idm-family", "electronic", "electronic", "IDM and experimental electronic", [], [], null, null],
  ["synthwave-family", "electronic", "electronic", "Synthwave and chip", [], [], null, null],
  ["caribbean", null, "americas", "Reggae and Caribbean", [], [], null, null],
  ["jamaican", "caribbean", "americas", "Jamaican", [], [], null, null],
  ["trinidad", "caribbean", "americas", "Trinidad and Eastern Caribbean", [], [], null, null],
  ["french-caribbean", "caribbean", "americas", "French and Haitian Caribbean", [], [], null, null],
  ["latin-america", null, "americas", "Latin America", ["Latin"], [], null, null],
  ["cuban", "latin-america", "americas", "Cuban", [], [], null, null],
  ["puerto-rico-dr", "latin-america", "americas", "Puerto Rico, Dominican Republic and salsa", [], [], null, null],
  ["mexican", "latin-america", "americas", "Mexico and borderlands", [], [], null, null],
  ["colombia-venezuela", "latin-america", "americas", "Colombia and Venezuela", [], [], null, null],
  ["andean", "latin-america", "americas", "Andes", [], [], null, null],
  ["southern-cone", "latin-america", "americas", "Southern Cone", [], [], null, null],
  ["brazil", "latin-america", "americas", "Brazil", [], [], null, null],
  ["africa", null, "africa-mena-southasia", "Sub-Saharan Africa", ["African"], [], null, null],
  ["west-africa", "africa", "africa-mena-southasia", "West Africa", [], [], null, null],
  ["central-africa", "africa", "africa-mena-southasia", "Central Africa", [], [], null, null],
  ["east-africa", "africa", "africa-mena-southasia", "East Africa and Horn", [], [], null, null],
  ["southern-africa", "africa", "africa-mena-southasia", "Southern Africa", [], [], null, null],
  ["mena", null, "africa-mena-southasia", "Middle East and North Africa", [], [], null, null],
  ["arabic-maqam", "mena", "africa-mena-southasia", "Arabic maqam traditions", [], [], null, null],
  ["persian-turkic", "mena", "africa-mena-southasia", "Persian, Turkish and Caucasus", [], [], null, null],
  ["jewish", "mena", "africa-mena-southasia", "Jewish traditions", [], [], null, null],
  ["south-asia", null, "africa-mena-southasia", "South Asia", [], [], null, null],
  ["hindustani", "south-asia", "africa-mena-southasia", "Hindustani classical", ["Indian Classical"], [], null, null],
  ["carnatic", "south-asia", "africa-mena-southasia", "Carnatic classical", [], [], null, null],
  ["south-asian-popular", "south-asia", "africa-mena-southasia", "South Asian folk and popular", [], [], null, null],
  ["europe-folk", null, "europe-asia-pacific", "European folk traditions", [], [], null, null],
  ["celtic-british", "europe-folk", "europe-asia-pacific", "Celtic and British Isles", ["Celtic"], [], null, null],
  ["nordic-baltic", "europe-folk", "europe-asia-pacific", "Nordic and Baltic", [], [], null, null],
  ["west-europe", "europe-folk", "europe-asia-pacific", "Western and Alpine Europe", [], [], null, null],
  ["iberia", "europe-folk", "europe-asia-pacific", "Iberia", [], [], null, null],
  ["central-east-europe", "europe-folk", "europe-asia-pacific", "Central and Eastern Europe", [], [], null, null],
  ["balkans-mediterranean", "europe-folk", "europe-asia-pacific", "Balkans and Eastern Mediterranean", [], [], null, null],
  ["east-asia", null, "europe-asia-pacific", "East Asia", [], [], null, null],
  ["china", "east-asia", "europe-asia-pacific", "China", [], [], null, null],
  ["japan", "east-asia", "europe-asia-pacific", "Japan", [], [], null, null],
  ["korea", "east-asia", "europe-asia-pacific", "Korea", [], [], null, null],
  ["central-north-asia", "east-asia", "europe-asia-pacific", "Mongolia and Siberia", [], [], null, null],
  ["southeast-asia", null, "europe-asia-pacific", "Southeast Asia", [], [], null, null],
  ["oceania", null, "europe-asia-pacific", "Oceania", [], [], null, null],
  ["plainchant", "early-music", "art", "Gregorian chant", ["Gregorian", "chant"], ["europe"], 600, 1200],
  ["byzantine-chant", "early-music", "art", "Byzantine and Orthodox chant", ["Byzantine", "znamenny", "orthodox chant"], ["balkans"], 500, 1700],
  ["organum", "early-music", "art", "Organum and Notre Dame school", ["ars antiqua", "notre dame school", "conductus"], [], 900, 1300],
  ["ars-nova", "early-music", "art", "Ars nova", ["Formes Fixes", "isorhythmic motet", "ars subtilior"], [], 1310, 1420],
  ["troubadour", "early-music", "art", "Troubadour and trouvere song", ["trouvere", "minnesang", "cantigas", "medieval song"], [], 1100, 1300],
  ["medieval-dance", "early-music", "art", "Medieval dance", ["estampie", "saltarello", "istampitta"], [], 1200, 1400],
  ["franco-flemish", "early-music", "art", "Franco-Flemish polyphony", ["renaissance polyphony", "josquin", "Magnificat", "Mass", "Motet", "Te Deum"], [], 1450, 1560],
  ["roman-school", "early-music", "art", "Roman school polyphony", ["palestrina style", "stile antico"], [], 1550, 1620],
  ["venetian-polychoral", "early-music", "art", "Venetian polychoral", ["cori spezzati", "gabrieli"], [], 1570, 1620],
  ["madrigal", "early-music", "art", "Renaissance madrigal", ["frottola", "villanella"], [], 1530, 1620],
  ["lute-song", "early-music", "art", "Lute song and air de cour", ["english ayre", "air de cour", "vihuela song"], [], 1590, 1630],
  ["iberian-renaissance", "early-music", "art", "Iberian Renaissance and colonial baroque", ["Villancicos", "villancico", "cancionero", "hispanic baroque"], ["iberia", "latin-america"], 1480, 1750],
  ["renaissance-dance", "early-music", "art", "Renaissance dance music", ["pavane", "galliard", "branle", "basse danse", "Dances"], [], 1450, 1620],
  ["early-baroque", "baroque", "art", "Early Baroque monody", ["seconda pratica", "monody", "stile rappresentativo"], [], 1600, 1650],
  ["italian-baroque", "baroque", "art", "Italian Baroque concerto and sonata", ["Concerto Grosso", "vivaldi", "corelli", "ritornello", "Concerto", "String Instrument"], [], 1650, 1750],
  ["french-baroque", "baroque", "art", "French Baroque", ["lully", "rameau", "tragedie lyrique", "ouverture"], [], 1650, 1760],
  ["german-baroque", "baroque", "art", "German Baroque counterpoint", ["bach fugue", "bach cantata", "fugue", "chorale prelude", "Cantata", "Passion", "Organ"], [], 1680, 1750],
  ["english-baroque", "baroque", "art", "English Baroque", ["purcell", "handel oratorio", "ground bass", "Oratorio"], [], 1660, 1760],
  ["opera-seria", "baroque", "art", "Baroque opera seria", ["da capo aria"], [], 1680, 1770],
  ["harpsichord-suite", "baroque", "art", "Baroque keyboard suite", ["Harpsichord", "dance suite", "allemande", "courante", "Keyboard", "Suite"], [], 1650, 1760],
  ["style-galant", "classical-period", "art", "Galant style", ["galant", "empfindsamkeit", "rococo"], [], 1720, 1780],
  ["viennese-classical", "classical-period", "art", "Viennese Classical", ["sonata form", "haydn", "mozart", "Divertimento", "Serenade", "Chamber Music", "Sonata", "Theme With Variations", "String Ensemble"], [], 1770, 1820],
  ["opera-buffa", "classical-period", "art", "Opera buffa", ["buffa", "dramma giocoso"], [], 1740, 1810],
  ["singspiel", "classical-period", "art", "Singspiel", [], [], 1760, 1830],
  ["early-romantic", "romantic", "art", "Early Romantic symphonic", ["beethoven", "heroic style"], [], 1800, 1830],
  ["romantic-miniature", "romantic", "art", "Romantic piano miniature", ["Nocturne", "romantic nocturne", "chopin", "character piece", "Etude", "Prelude", "Capriccio", "Fantasia", "Piano"], [], 1820, 1890],
  ["lied", "romantic", "art", "Lied and art song", ["Art Song", "melodie", "romance"], [], 1810, 1920],
  ["bel-canto", "romantic", "art", "Bel canto opera", [], [], 1805, 1850],
  ["grand-opera", "romantic", "art", "French grand opera", ["Opera"], [], 1828, 1870],
  ["music-drama", "romantic", "art", "Wagnerian music drama", ["leitmotif", "wagner"], [], 1850, 1890],
  ["verismo", "romantic", "art", "Verismo", [], [], 1890, 1925],
  ["romantic-symphonic", "romantic", "art", "Romantic symphonic", ["brahms", "symphony", "absolute music", "Orchestra", "Overture"], [], 1830, 1900],
  ["tone-poem", "romantic", "art", "Program music and tone poem", ["Program Music", "symphonic poem", "Rhapsody"], [], 1840, 1920],
  ["nationalist-romantic", "romantic", "art", "Romantic nationalism", ["nationalist school", "mighty handful", "grieg", "dvorak", "Classical Guitar"], [], 1850, 1920],
  ["late-romantic", "romantic", "art", "Late Romantic", ["mahler", "post-romantic"], [], 1880, 1920],
  ["operetta", "romantic", "art", "Operetta", ["viennese operetta", "savoy opera"], [], 1855, 1930],
  ["zarzuela", "romantic", "art", "Zarzuela", ["genero chico"], ["spain"], 1850, 1950],
  ["salon-music", "romantic", "art", "Salon and Biedermeier music", ["salon piece", "parlour music"], [], 1820, 1910],
  ["impressionism", "modern-art", "art", "Impressionism", ["Impressionist", "debussy", "ravel"], [], 1890, 1930],
  ["expressionism", "modern-art", "art", "Expressionism and free atonality", ["Expressionist", "Atonal", "free atonality"], [], 1908, 1925],
  ["twelve-tone", "modern-art", "art", "Twelve-tone", ["dodecaphony", "second viennese school"], [], 1921, 1960],
  ["integral-serialism", "modern-art", "art", "Integral serialism", ["Serial", "total serialism", "darmstadt"], [], 1949, 1970],
  ["neoclassicism", "modern-art", "art", "Neoclassicism", ["Neo-Classical", "stravinsky neoclassical"], [], 1920, 1955],
  ["primitivism", "modern-art", "art", "Primitivism and motor rhythm", ["rite of spring", "barbarism"], [], 1910, 1930],
  ["futurism", "modern-art", "art", "Futurism", ["intonarumori", "bruitism"], [], 1910, 1930],
  ["folk-modernism", "modern-art", "art", "Folk-based modernism", ["bartok", "kodaly", "janacek"], [], 1905, 1950],
  ["soviet-modernism", "modern-art", "art", "Soviet symphonic", ["shostakovich", "prokofiev", "socialist realism"], [], 1925, 1975],
  ["modal-mysticism", "modern-art", "art", "Modal mysticism", ["messiaen", "modes of limited transposition", "birdsong"], [], 1930, 1990],
  ["american-modernism", "modern-art", "art", "American ultramodernism and Americana", ["ives", "cowell", "copland", "ultramodernism", "Percussion Ensemble"], [], 1910, 1960],
  ["neo-romantic", "modern-art", "art", "Neo-Romantic", [], [], 1920, 2000],
  ["aleatoric", "contemporary-art", "art", "Aleatoric and indeterminate", ["chance music", "indeterminacy", "graphic score"], [], 1950, 1980],
  ["sonorism", "contemporary-art", "art", "Sonorism and texture music", ["micropolyphony", "ligeti", "penderecki", "sound mass"], [], 1955, 1980],
  ["spectralism", "contemporary-art", "art", "Spectralism", ["spectral music"], [], 1973, null],
  ["new-complexity", "contemporary-art", "art", "New complexity", ["ferneyhough", "complexism"], [], 1975, null],
  ["drone-minimalism", "contemporary-art", "art", "Drone minimalism", ["la monte young", "just intonation drone", "dream house"], [], 1958, null],
  ["pulse-minimalism", "contemporary-art", "art", "Pulse and process minimalism", ["Minimalism", "phasing", "steve reich", "process music"], [], 1964, null],
  ["additive-minimalism", "contemporary-art", "art", "Additive repetitive minimalism", ["philip glass", "additive process"], [], 1967, null],
  ["holy-minimalism", "contemporary-art", "art", "Holy minimalism", ["tintinnabuli", "arvo part", "mystic minimalism"], [], 1976, null],
  ["choral-art", "contemporary-art", "art", "Contemporary choral", ["Choral", "Requiem", "choral cluster", "a cappella choir"], [], 1960, null],
  ["postminimalism", "contemporary-art", "art", "Postminimalism", ["post-minimalism", "totalism"], [], 1980, null],
  ["polystylism", "contemporary-art", "art", "Postmodern polystylism", ["Post-Modern", "collage"], [], 1965, null],
  ["microtonal-art", "contemporary-art", "art", "Microtonal and just intonation", ["Microtonal", "just intonation", "harry partch", "xenharmonic"], [], 1920, null],
  ["modern-classical", "contemporary-art", "art", "Contemporary neoclassical", ["post-classical", "neoclassical piano", "Classical Crossover"], [], 2000, null],
  ["military-march", "concert-band", "art", "Military march", ["Marches", "Military", "march", "sousa"], [], 1700, null],
  ["brass-band", "concert-band", "art", "Brass band", ["british brass band", "colliery band", "Brass Instrument", "Guggenmusik"], [], 1840, null],
  ["concert-wind-band", "concert-band", "art", "Concert wind band", ["Wind Ensemble", "symphonic band", "Woodwind Instrument"], [], 1900, null],
  ["pipe-band", "concert-band", "art", "Pipe band", ["Pipe & Drum", "pipes and drums"], ["scotland"], null, null],
  ["marching-band", "concert-band", "art", "Marching band and drumline", ["drumline", "hbcu marching", "drum corps", "Sport"], ["usa"], null, null],
  ["musique-concrete", "experimental", "art", "Musique concrete", ["Musique Concrète", "acousmatic", "tape music"], [], 1948, null],
  ["elektronische-musik", "experimental", "art", "Early studio electronic", ["tape studio", "radiophonic"], [], 1951, 1975],
  ["electroacoustic", "experimental", "art", "Electroacoustic composition", ["acousmatique", "computer music"], [], 1960, null],
  ["sound-collage", "experimental", "art", "Sound collage and plunderphonics", ["Plunderphonics"], [], 1960, null],
  ["free-improvisation", "experimental", "art", "Free improvisation", ["eai", "electroacoustic improvisation", "Solo"], [], 1965, null],
  ["onkyo", "experimental", "art", "Onkyo and lowercase", ["Lowercase", "onkyokei", "reductionism", "wandelweiser"], [], 1995, null],
  ["drone", "experimental", "art", "Drone", ["drone music"], [], 1960, null],
  ["harsh-noise", "experimental", "art", "Harsh noise", ["Noise", "japanoise", "noise music"], [], 1975, null],
  ["harsh-noise-wall", "experimental", "art", "Harsh noise wall", ["hnw"], [], 2000, null],
  ["power-electronics", "experimental", "art", "Power electronics", ["death industrial"], [], 1980, null],
  ["field-recording", "experimental", "art", "Field recording and soundscape", ["soundscape", "phonography"], [], 1960, null],
  ["sound-art", "experimental", "art", "Sound art and installation", ["installation"], [], 1960, null],
  ["sound-poetry", "experimental", "art", "Sound poetry", ["lautgedicht"], [], 1916, null],
  ["spoken-word", "experimental", "art", "Spoken word", ["Poetry", "Speech", "Monolog", "Audiobook", "Story", "Radioplay", "Comedy", "Dialogue", "Interview", "Erotic"], [], 1900, null],
  ["glitch-art", "experimental", "art", "Glitch and microsound", ["microsound", "clicks and cuts"], [], 1994, null],
  ["algorithmic", "experimental", "art", "Algorithmic and generative", ["generative music", "live coding", "algorave", "Abstract"], [], 1957, null],
  ["golden-age-score", "screen-stage", "art", "Golden age film score", ["Score", "Soundtrack", "hollywood symphonic", "leitmotif score"], [], 1933, 1960],
  ["modern-orchestral-score", "screen-stage", "art", "Modern orchestral film score", ["blockbuster score", "Theme", "thematic score"], [], 1975, null],
  ["hybrid-trailer", "screen-stage", "art", "Hybrid trailer and epic", ["trailer music", "epic orchestral", "braaam"], [], 2005, null],
  ["synth-score", "screen-stage", "art", "Synth film score", ["carpenter synth score", "synth soundtrack"], [], 1975, null],
  ["western-score", "screen-stage", "art", "Western score", ["spaghetti western", "morricone western"], [], 1960, 1975],
  ["horror-score", "screen-stage", "art", "Horror and suspense score", ["suspense", "giallo"], [], 1960, null],
  ["ambient-score", "screen-stage", "art", "Minimal ambient score", ["drone score", "prestige tv"], [], 2000, null],
  ["library-music", "screen-stage", "art", "Library and production music", ["production music", "Promotional", "Public Broadcast", "Public Service Announcement"], [], 1960, null],
  ["incidental", "screen-stage", "art", "Incidental and cue music", ["Incidental Music", "underscore", "Music Video", "Concert Film"], [], 1900, null],
  ["sound-design", "screen-stage", "art", "Sound design and foley", ["Movie Effects", "Special Effects", "foley", "sfx", "Technical"], [], 1930, null],
  ["musical-theatre-golden", "screen-stage", "art", "Golden age musical theatre", ["Musical", "broadway", "show tune"], [], 1927, 1970],
  ["contemporary-musical", "screen-stage", "art", "Contemporary musical theatre", ["pop musical", "megamusical", "rock musical"], [], 1970, null],
  ["cabaret", "screen-stage", "art", "Cabaret", ["kabarett"], [], 1880, null],
  ["vaudeville", "screen-stage", "art", "Vaudeville", ["minstrel stage"], [], 1880, 1932],
  ["ballet-score", "screen-stage", "art", "Ballet and dance score", ["Ballet"], [], 1830, null],
  ["orchestral-game", "screen-stage", "art", "Orchestral game score", ["Video Game Music", "game score", "adaptive score"], [], 1995, null],
  ["jrpg", "screen-stage", "art", "JRPG and console game", ["battle theme", "console rpg"], [], 1986, null],
  ["anime-score", "screen-stage", "art", "Anime score and anison", ["Anison", "anime song", "anime soundtrack"], ["japan"], 1963, null],
  ["childrens-song", "childrens", "art", "Children's song", ["Nursery Rhymes", "Educational", "children's", "Lullaby", "Education"], [], 1800, null],
  ["novelty", "childrens", "art", "Novelty and comedy song", ["Parody", "Break-In", "Filk", "comedy song"], [], 1900, null],
  ["wellness", "childrens", "art", "Meditation and wellness", ["Therapy", "Health-Fitness", "Medical", "meditation music", "healing"], [], 1970, null],
  ["ragtime", "early-jazz", "roots", "Ragtime", ["cakewalk", "classic rag"], ["usa"], 1895, 1920],
  ["new-orleans-jazz", "early-jazz", "roots", "New Orleans jazz", ["Dixieland", "trad jazz", "hot jazz", "traditional jazz"], [], 1910, 1935],
  ["chicago-jazz", "early-jazz", "roots", "Chicago-style jazz", ["chicago dixieland", "austin high"], [], 1920, 1935],
  ["stride", "early-jazz", "roots", "Stride piano", ["harlem stride"], [], 1920, 1940],
  ["big-band-swing", "swing-era", "roots", "Big band swing", ["Swing", "Big Band", "dance band"], [], 1930, 1950],
  ["kansas-city-jazz", "swing-era", "roots", "Kansas City jazz", ["kansas city swing", "riff band"], [], 1925, 1945],
  ["gypsy-jazz", "swing-era", "roots", "Gypsy jazz", ["jazz manouche", "hot club"], ["france"], 1934, null],
  ["vocal-jazz", "swing-era", "roots", "Vocal jazz and standards", ["jazz standards", "jazz vocal", "scat"], [], 1930, null],
  ["bebop", "modern-jazz", "roots", "Bebop", ["Bop"], [], 1942, 1955],
  ["cool-jazz", "modern-jazz", "roots", "Cool jazz", ["west coast jazz"], [], 1949, 1960],
  ["hard-bop", "modern-jazz", "roots", "Hard bop", [], [], 1953, 1965],
  ["soul-jazz", "modern-jazz", "roots", "Soul jazz", ["organ jazz", "groove jazz"], [], 1957, 1975],
  ["modal-jazz", "modern-jazz", "roots", "Modal jazz", ["Modal"], [], 1958, null],
  ["post-bop", "modern-jazz", "roots", "Post-bop", [], [], 1960, null],
  ["third-stream", "modern-jazz", "roots", "Third stream", [], [], 1957, null],
  ["chamber-jazz", "modern-jazz", "roots", "Chamber and ECM jazz", ["ecm", "nordic jazz"], [], 1970, null],
  ["contemporary-jazz", "modern-jazz", "roots", "Contemporary jazz", ["modern mainstream"], [], 1985, null],
  ["uk-jazz", "modern-jazz", "roots", "UK jazz new wave", ["london jazz", "south london jazz"], ["uk"], 2012, null],
  ["free-jazz", "avant-jazz", "roots", "Free jazz", ["new thing"], [], 1959, null],
  ["avant-garde-jazz", "avant-jazz", "roots", "Avant-garde jazz", ["loft jazz", "creative music"], [], 1965, null],
  ["spiritual-jazz", "avant-jazz", "roots", "Spiritual jazz", ["cosmic jazz"], [], 1965, null],
  ["dark-jazz", "avant-jazz", "roots", "Dark jazz", ["doom jazz", "noir jazz"], [], 1995, null],
  ["jazz-fusion", "jazz-fusion-family", "roots", "Jazz fusion", ["Fusion", "Jazz-Rock"], [], 1969, null],
  ["jazz-funk", "jazz-fusion-family", "roots", "Jazz-funk", [], [], 1972, null],
  ["smooth-jazz", "jazz-fusion-family", "roots", "Smooth jazz", ["quiet storm jazz", "crossover jazz"], [], 1980, null],
  ["acid-jazz", "jazz-fusion-family", "roots", "Acid jazz", ["jazz dance", "Jazzdance"], ["uk"], 1987, null],
  ["nu-jazz", "jazz-fusion-family", "roots", "Nu jazz", ["Future Jazz", "electro jazz"], [], 1995, null],
  ["afro-cuban-jazz", "jazz-fusion-family", "roots", "Afro-Cuban jazz", ["cubop"], ["cuba", "usa"], 1947, null],
  ["latin-jazz", "jazz-fusion-family", "roots", "Brazilian and pan-Latin jazz", ["brazilian jazz", "samba jazz"], [], 1960, null],
  ["delta-blues", "acoustic-blues", "roots", "Delta blues", [], ["mississippi"], 1920, null],
  ["piedmont-blues", "acoustic-blues", "roots", "Piedmont blues", ["East Coast Blues"], ["southeast-usa"], 1920, null],
  ["texas-blues", "acoustic-blues", "roots", "Texas blues", [], ["texas"], 1920, null],
  ["hill-country-blues", "acoustic-blues", "roots", "Hill country blues", ["north mississippi"], ["mississippi"], 1960, null],
  ["memphis-blues", "acoustic-blues", "roots", "Memphis blues", [], ["tennessee"], 1920, null],
  ["jug-band", "acoustic-blues", "roots", "Jug band", ["washboard band"], [], 1920, 1940],
  ["classic-female-blues", "acoustic-blues", "roots", "Classic vaudeville blues", ["classic blues", "vaudeville blues"], [], 1920, 1935],
  ["piano-blues", "urban-blues", "roots", "Barrelhouse and piano blues", ["barrelhouse"], [], 1920, null],
  ["boogie-woogie", "urban-blues", "roots", "Boogie-woogie", [], [], 1925, null],
  ["jump-blues", "urban-blues", "roots", "Jump blues", [], [], 1940, 1955],
  ["chicago-blues", "urban-blues", "roots", "Chicago blues", ["Electric Blues", "Harmonica Blues", "west side blues"], ["chicago"], 1945, null],
  ["louisiana-blues", "urban-blues", "roots", "Louisiana and swamp blues", ["swamp blues"], ["louisiana"], 1950, null],
  ["west-coast-blues", "urban-blues", "roots", "West Coast blues", ["t-bone", "west coast jump"], [], 1945, null],
  ["soul-blues", "urban-blues", "roots", "Soul blues", ["southern soul blues", "chitlin circuit"], [], 1965, null],
  ["modern-electric-blues", "urban-blues", "roots", "Modern electric blues", ["contemporary blues"], [], 1980, null],
  ["classic-rnb", "rhythm-and-blues", "roots", "Classic rhythm and blues", ["Rhythm & Blues", "r&b 1950s"], [], 1945, 1962],
  ["doo-wop", "rhythm-and-blues", "roots", "Doo-wop", ["street corner harmony"], [], 1950, 1963],
  ["new-orleans-rnb", "rhythm-and-blues", "roots", "New Orleans R&B", ["crescent city r&b", "second line r&b"], [], 1950, 1965],
  ["southern-soul", "soul", "roots", "Southern soul", ["memphis soul", "stax", "muscle shoals", "deep soul"], [], 1960, 1975],
  ["motown", "soul", "roots", "Motown", ["detroit soul", "motown sound"], [], 1960, 1975],
  ["chicago-soul", "soul", "roots", "Chicago soul", [], [], 1960, 1975],
  ["northern-soul", "soul", "roots", "Northern soul", ["rare soul"], ["uk"], 1965, null],
  ["philly-soul", "soul", "roots", "Philadelphia soul", ["sweet soul"], [], 1968, 1980],
  ["psychedelic-soul", "soul", "roots", "Psychedelic soul", ["Psychedelic"], [], 1967, 1975],
  ["quiet-storm", "soul", "roots", "Quiet storm", ["slow jam"], [], 1975, null],
  ["neo-soul", "soul", "roots", "Neo soul", [], [], 1994, null],
  ["uk-street-soul", "soul", "roots", "UK street soul", [], ["uk"], 1985, 1995],
  ["contemporary-rnb", "modern-rnb", "roots", "Contemporary R&B", ["urban contemporary"], [], 1980, null],
  ["new-jack-swing", "modern-rnb", "roots", "New jack swing", ["Swingbeat"], [], 1987, 1995],
  ["hip-hop-soul", "modern-rnb", "roots", "Hip hop soul and 90s R&B", ["RnB/Swing"], [], 1992, 2005],
  ["alternative-rnb", "modern-rnb", "roots", "Alternative R&B", ["pbr&b", "alt r&b", "dark r&b"], [], 2010, null],
  ["classic-funk", "funk", "roots", "Classic funk", ["james brown funk", "the one"], [], 1965, null],
  ["p-funk", "funk", "roots", "P-Funk", ["parliament funk"], [], 1970, 1985],
  ["bayou-funk", "funk", "roots", "New Orleans and bayou funk", ["meters funk"], [], 1968, null],
  ["go-go", "funk", "roots", "Go-go", ["Gogo"], ["washington-dc"], 1975, null],
  ["minneapolis-sound", "funk", "roots", "Minneapolis sound", [], [], 1979, 1990],
  ["boogie", "funk", "roots", "Boogie and post-disco", ["post-disco"], [], 1979, 1986],
  ["free-funk", "funk", "roots", "Free funk", ["harmolodic funk"], [], 1975, null],
  ["funk-band", "funk", "roots", "Big-band and soul revue funk", ["deep funk", "rare groove", "soul revue"], [], 1968, null],
  ["traditional-gospel", "gospel-sacred", "roots", "Traditional black gospel", ["Gospel", "black gospel"], [], 1930, null],
  ["gospel-quartet", "gospel-sacred", "roots", "Gospel quartet", ["quartet gospel", "jubilee"], [], 1920, null],
  ["urban-gospel", "gospel-sacred", "roots", "Urban contemporary gospel", ["contemporary gospel"], [], 1975, null],
  ["southern-gospel", "gospel-sacred", "roots", "Southern gospel", ["convention singing"], [], 1910, null],
  ["spirituals", "gospel-sacred", "roots", "Spirituals", ["negro spiritual", "ring shout"], [], 1800, null],
  ["ccm", "gospel-sacred", "roots", "Contemporary Christian", ["christian rock", "christian pop", "Religious", "Sermon"], [], 1970, null],
  ["worship", "gospel-sacred", "roots", "Praise and worship", ["praise", "hillsong"], [], 1990, null],
  ["old-time", "country", "roots", "Old-time", ["string band", "Hillbilly"], [], 1920, null],
  ["bluegrass", "country", "roots", "Bluegrass", [], [], 1945, null],
  ["progressive-bluegrass", "country", "roots", "Progressive bluegrass", ["newgrass"], [], 1965, null],
  ["western-swing", "country", "roots", "Western swing", [], [], 1930, null],
  ["honky-tonk", "country", "roots", "Honky tonk", [], [], 1945, null],
  ["nashville-sound", "country", "roots", "Nashville sound and countrypolitan", ["countrypolitan"], [], 1957, 1980],
  ["bakersfield", "country", "roots", "Bakersfield sound", [], [], 1955, 1975],
  ["outlaw-country", "country", "roots", "Outlaw country", ["outlaw"], [], 1970, null],
  ["cowboy-western", "country", "roots", "Cowboy and western song", ["singing cowboy", "western"], [], 1930, null],
  ["country-pop", "country", "roots", "Country pop and modern Nashville", ["contemporary country", "bro-country"], [], 1990, null],
  ["alt-country", "country", "roots", "Alt-country and Americana", ["americana", "Country Rock"], [], 1985, null],
  ["texas-red-dirt", "country", "roots", "Texas country and red dirt", ["red dirt", "texas country"], [], 1975, null],
  ["appalachian", "north-american-folk", "roots", "Appalachian ballad", ["Appalachian Music", "mountain ballad", "child ballad"], [], 1700, null],
  ["sacred-harp", "north-american-folk", "roots", "Sacred harp and shape note", ["shape note", "fasola"], [], 1800, null],
  ["american-folk-revival", "north-american-folk", "roots", "Folk revival", ["Folk", "protest song", "Political"], [], 1940, null],
  ["singer-songwriter", "north-american-folk", "roots", "Singer-songwriter", ["confessional", "Acoustic"], [], 1965, null],
  ["contemporary-folk", "north-american-folk", "roots", "Contemporary folk and indie folk", ["indie folk", "freak folk", "new weird america", "Antifolk"], [], 1995, null],
  ["cajun", "north-american-folk", "roots", "Cajun", ["cajun french"], ["louisiana"], 1920, null],
  ["zydeco", "north-american-folk", "roots", "Zydeco", [], ["louisiana"], 1950, null],
  ["swamp-pop", "north-american-folk", "roots", "Swamp pop", [], ["louisiana"], 1955, null],
  ["native-american", "north-american-folk", "roots", "Native American powwow and song", ["powwow", "native american flute", "peyote song"], ["north-america"], null, null],
  ["inuit-throat", "north-american-folk", "roots", "Inuit katajjaq", ["katajjaq", "inuit throat singing"], ["arctic"], null, null],
  ["sea-shanty", "north-american-folk", "roots", "Sea shanty", ["Sea Shanties", "work song"], [], 1800, null],
  ["barbershop", "north-american-folk", "roots", "Barbershop", ["barbershop quartet"], [], 1890, null],
  ["rock-and-roll", "early-rock", "rock", "Rock and roll", ["Rock & Roll"], [], 1954, 1963],
  ["rockabilly", "early-rock", "rock", "Rockabilly", ["Neo-Rockabilly"], [], 1954, null],
  ["skiffle", "early-rock", "rock", "Skiffle", [], ["uk"], 1950, 1960],
  ["surf", "early-rock", "rock", "Surf rock", [], [], 1961, null],
  ["twist", "early-rock", "rock", "Twist and dance craze", ["Hully gully", "madison"], [], 1959, 1965],
  ["beat", "early-rock", "rock", "Beat and British invasion", ["Merseybeat", "british invasion", "Mod", "Group Sounds"], [], 1962, 1968],
  ["garage-rock", "early-rock", "rock", "Garage rock", ["garage punk"], [], 1963, null],
  ["instrumental-rock", "early-rock", "rock", "Instrumental rock", ["rock instrumental", "twang"], [], 1958, null],
  ["psychedelic-rock", "classic-rock", "rock", "Psychedelic rock", ["acid rock"], [], 1966, null],
  ["blues-rock", "classic-rock", "rock", "Blues rock", ["british blues"], [], 1965, null],
  ["hard-rock", "classic-rock", "rock", "Hard rock", ["AOR", "arena rock"], [], 1968, null],
  ["southern-rock", "classic-rock", "rock", "Southern rock", [], [], 1970, null],
  ["glam-rock", "classic-rock", "rock", "Glam rock", ["Glam", "glitter rock"], [], 1971, 1976],
  ["pub-rock", "classic-rock", "rock", "Pub rock", [], ["uk"], 1971, 1977],
  ["soft-rock", "classic-rock", "rock", "Soft rock and yacht rock", ["yacht rock", "west coast"], [], 1970, null],
  ["heartland-rock", "classic-rock", "rock", "Heartland rock", ["heartland"], [], 1975, null],
  ["stoner-rock", "classic-rock", "rock", "Stoner and desert rock", ["desert rock"], [], 1990, null],
  ["folk-rock", "classic-rock", "rock", "Folk rock", ["electric folk"], [], 1965, null],
  ["pop-rock", "classic-rock", "rock", "Pop rock", [], [], 1965, null],
  ["roots-rock", "classic-rock", "rock", "Roots rock", ["Swamp rock"], [], 1968, null],
  ["prog-rock", "prog", "rock", "Progressive rock", ["symphonic prog", "Symphonic Rock"], [], 1968, null],
  ["art-rock", "prog", "rock", "Art rock", ["Rock Opera"], [], 1966, null],
  ["canterbury", "prog", "rock", "Canterbury scene", [], ["uk"], 1967, 1978],
  ["krautrock", "prog", "rock", "Krautrock", ["motorik", "kosmische"], ["germany"], 1968, 1980],
  ["space-rock", "prog", "rock", "Space rock", [], [], 1969, null],
  ["zeuhl", "prog", "rock", "Zeuhl and RIO", ["rock in opposition", "avant-prog"], [], 1970, null],
  ["jam-band", "prog", "rock", "Jam band", [], [], 1965, null],
  ["indie-rock", "alt-indie", "rock", "Indie rock", ["Alternative Rock", "college rock"], [], 1983, null],
  ["jangle-pop", "alt-indie", "rock", "Jangle pop", ["c86"], [], 1980, null],
  ["shoegaze", "alt-indie", "rock", "Shoegaze", ["nu-gaze"], [], 1988, null],
  ["dream-pop", "alt-indie", "rock", "Dream pop", ["Ethereal"], [], 1983, null],
  ["noise-rock", "alt-indie", "rock", "Noise rock", [], [], 1985, null],
  ["grunge", "alt-indie", "rock", "Grunge", ["Post-Grunge"], [], 1987, null],
  ["britpop", "alt-indie", "rock", "Britpop", ["Brit Pop"], ["uk"], 1993, 1998],
  ["math-rock", "alt-indie", "rock", "Math rock", [], [], 1988, null],
  ["post-rock", "alt-indie", "rock", "Post-rock", [], [], 1991, null],
  ["slowcore", "alt-indie", "rock", "Slowcore and sadcore", ["sadcore"], [], 1990, null],
  ["lo-fi-indie", "alt-indie", "rock", "Lo-fi indie", ["Lo-Fi", "bedroom rock"], [], 1985, null],
  ["garage-revival", "alt-indie", "rock", "Garage revival and post-punk revival", ["post-punk revival", "indie sleaze"], [], 2000, null],
  ["midwest-emo", "alt-indie", "rock", "Midwest emo", ["twinkle emo"], [], 1993, null],
  ["emo", "alt-indie", "rock", "Emo and emo pop", ["emocore"], [], 1985, null],
  ["indie-songwriter", "alt-indie", "rock", "Indie songwriter rock", ["Mitski", "bedroom indie"], [], 2010, null],
  ["j-rock", "alt-indie", "rock", "J-rock and visual kei", ["visual kei"], ["japan"], null, null],
  ["k-rock", "alt-indie", "rock", "K-rock", [], ["korea"], null, null],
  ["anatolian-rock", "alt-indie", "rock", "Anatolian rock", [], ["turkey"], 1965, null],
  ["proto-punk", "punk", "rock", "Proto-punk", [], [], 1965, 1975],
  ["punk-rock", "punk", "rock", "Punk rock", ["punk 77", "first wave punk"], [], 1975, null],
  ["oi", "punk", "rock", "Oi! and street punk", ["street punk"], [], 1979, null],
  ["hardcore-punk", "punk", "rock", "Hardcore punk", ["Hardcore", "melodic hardcore", "youth crew"], [], 1980, null],
  ["crust", "punk", "rock", "Crust and d-beat", ["d-beat"], [], 1984, null],
  ["anarcho-punk", "punk", "rock", "Anarcho-punk", [], [], 1978, null],
  ["pop-punk", "punk", "rock", "Pop punk", [], [], 1977, null],
  ["skate-punk", "punk", "rock", "Skate punk", ["melodic punk"], [], 1985, null],
  ["post-punk", "punk", "rock", "Post-punk", [], [], 1978, null],
  ["no-wave", "punk", "rock", "No wave", [], [], 1977, 1982],
  ["deathrock", "punk", "rock", "Deathrock", [], [], 1979, null],
  ["goth-rock", "punk", "rock", "Gothic rock", ["Gothic", "batcave"], [], 1980, null],
  ["coldwave", "punk", "rock", "Coldwave", ["cold wave"], ["france"], 1979, null],
  ["psychobilly", "punk", "rock", "Psychobilly", ["Horror Rock"], [], 1980, null],
  ["post-hardcore", "punk", "rock", "Post-hardcore", [], [], 1985, null],
  ["screamo", "punk", "rock", "Screamo", ["skramz"], [], 1991, null],
  ["powerviolence", "punk", "rock", "Powerviolence", ["Power Violence"], [], 1990, null],
  ["folk-punk", "punk", "rock", "Folk punk and celtic punk", ["celtic punk"], [], 1982, null],
  ["synthpunk", "punk", "rock", "Synth punk", ["egg punk"], [], 1977, null],
  ["heavy-metal", "metal", "rock", "Heavy metal", ["nwobhm", "traditional metal"], [], 1970, null],
  ["speed-metal", "metal", "rock", "Speed metal", [], [], 1982, null],
  ["thrash", "metal", "rock", "Thrash metal", ["Crossover Thrash"], [], 1983, null],
  ["power-metal", "metal", "rock", "Power metal", [], [], 1986, null],
  ["glam-metal", "metal", "rock", "Glam metal", ["hair metal", "pop metal"], [], 1983, 1991],
  ["doom-metal", "metal", "rock", "Doom metal", ["traditional doom", "epic doom"], [], 1980, null],
  ["funeral-doom", "metal", "rock", "Funeral doom", ["Funeral Doom Metal"], [], 1990, null],
  ["sludge", "metal", "rock", "Sludge metal", [], [], 1988, null],
  ["stoner-metal", "metal", "rock", "Stoner metal", ["stoner doom"], [], 1990, null],
  ["death-metal", "metal", "rock", "Death metal", ["old school death metal"], [], 1985, null],
  ["brutal-death", "metal", "rock", "Brutal and technical death metal", ["Brutal Death Metal", "Technical Death Metal", "slam"], [], 1990, null],
  ["melodic-death", "metal", "rock", "Melodic death metal", ["gothenburg"], [], 1993, null],
  ["black-metal", "metal", "rock", "Black metal", ["Depressive Black Metal", "atmospheric black metal", "Unblack Metal"], [], 1984, null],
  ["blackgaze", "metal", "rock", "Blackgaze", ["post-black metal"], [], 2005, null],
  ["viking-metal", "metal", "rock", "Viking and folk metal", ["Folk Metal", "pagan metal"], [], 1988, null],
  ["grindcore", "metal", "rock", "Grindcore", ["Goregrind", "Pornogrind", "Noisecore"], [], 1985, null],
  ["groove-metal", "metal", "rock", "Groove metal", [], [], 1990, null],
  ["nu-metal", "metal", "rock", "Nu metal and alt metal", ["Alternative Metal", "Funk Metal", "rap metal"], [], 1994, null],
  ["industrial-metal", "metal", "rock", "Industrial metal", [], [], 1988, null],
  ["gothic-metal", "metal", "rock", "Gothic and symphonic metal", ["Symphonic Metal"], [], 1992, null],
  ["neo-classical-metal", "metal", "rock", "Neoclassical metal", ["shred"], [], 1984, null],
  ["prog-metal", "metal", "rock", "Progressive metal", ["djent"], [], 1988, null],
  ["metalcore", "metal", "rock", "Metalcore", [], [], 1990, null],
  ["deathcore", "metal", "rock", "Deathcore", [], [], 2003, null],
  ["mathcore", "metal", "rock", "Mathcore", [], [], 1995, null],
  ["post-metal", "metal", "rock", "Post-metal", ["atmospheric sludge"], [], 1995, null],
  ["drone-metal", "metal", "rock", "Drone metal", ["drone doom"], [], 1990, null],
  ["nintendocore", "metal", "rock", "Nintendocore", [], [], 2000, null],
  ["tin-pan-alley", "traditional-pop", "pop", "Tin Pan Alley and standards", ["great american songbook", "Vocal", "Holiday"], [], 1890, 1955],
  ["crooner", "traditional-pop", "pop", "Crooner pop", ["Easy Listening"], [], 1930, 1965],
  ["lounge", "traditional-pop", "pop", "Lounge and space-age pop", ["space age pop", "Space-Age"], [], 1955, 1970],
  ["exotica", "traditional-pop", "pop", "Exotica", [], [], 1955, 1965],
  ["light-music", "traditional-pop", "pop", "Light orchestral music", ["mood music", "beautiful music"], [], 1930, null],
  ["schlager", "traditional-pop", "pop", "Schlager", ["volkstumliche schlager"], ["germany"], null, null],
  ["chanson", "traditional-pop", "pop", "Chanson", ["chanson francaise"], ["france"], null, null],
  ["canzone", "traditional-pop", "pop", "Canzone italiana", ["Italo pop", "sanremo"], ["italy"], null, null],
  ["european-pop-ballad", "traditional-pop", "pop", "Euro ballad and Eurovision", ["eurovision", "Europop"], ["europe"], null, null],
  ["musette", "traditional-pop", "pop", "Bal musette", [], ["france"], null, null],
  ["kayokyoku", "traditional-pop", "pop", "Kayokyoku", ["Kayōkyoku", "showa pop"], ["japan"], null, null],
  ["enka", "traditional-pop", "pop", "Enka", [], ["japan"], null, null],
  ["shidaiqu", "traditional-pop", "pop", "Shidaiqu", ["shanghai pop"], ["china"], 1920, 1950],
  ["trot", "traditional-pop", "pop", "Trot", ["ppongjjak"], ["korea"], null, null],
  ["brill-building", "sixties-pop", "pop", "Brill Building and girl group", ["girl group", "wall of sound"], [], 1958, 1966],
  ["sunshine-pop", "sixties-pop", "pop", "Sunshine and baroque pop", ["Baroque Pop", "chamber pop"], [], 1965, null],
  ["bubblegum", "sixties-pop", "pop", "Bubblegum", [], [], 1967, 1972],
  ["ye-ye", "sixties-pop", "pop", "Ye-ye", ["Yé-Yé"], ["france"], 1962, 1970],
  ["power-pop", "sixties-pop", "pop", "Power pop", [], [], 1970, null],
  ["new-wave", "modern-pop", "pop", "New wave", ["NDW", "neue deutsche welle"], [], 1978, 1986],
  ["synth-pop", "modern-pop", "pop", "Synth-pop", ["new romantic"], [], 1979, null],
  ["dance-pop", "modern-pop", "pop", "Dance-pop", ["club pop"], [], 1983, null],
  ["teen-pop", "modern-pop", "pop", "Teen pop and boy band", ["boy band"], [], 1988, null],
  ["adult-contemporary", "modern-pop", "pop", "Adult contemporary and ballad", ["Ballad", "power ballad", "Karaoke"], [], 1970, null],
  ["electropop", "modern-pop", "pop", "Electropop", [], [], 2005, null],
  ["latin-pop", "modern-pop", "pop", "Latin pop", ["balada", "pop latino"], [], 1970, null],
  ["indie-pop", "modern-pop", "pop", "Indie pop and twee", ["twee"], [], 1985, null],
  ["art-pop", "modern-pop", "pop", "Art pop", ["avant-pop"], [], 1975, null],
  ["bedroom-pop", "modern-pop", "pop", "Bedroom pop", [], [], 2015, null],
  ["alt-pop", "modern-pop", "pop", "Alt-pop and dark pop", ["dark pop"], [], 2012, null],
  ["chamber-pop-modern", "modern-pop", "pop", "Orchestral and chamber pop", ["orchestral pop"], [], 1995, null],
  ["hyperpop", "modern-pop", "pop", "Hyperpop", ["digicore"], [], 2018, null],
  ["pc-music", "modern-pop", "pop", "PC Music bubblegum bass", ["bubblegum bass"], [], 2013, null],
  ["shibuya-kei", "modern-pop", "pop", "Shibuya-kei", [], ["japan"], 1990, 2000],
  ["city-pop", "modern-pop", "pop", "City pop", [], ["japan"], 1977, 1990],
  ["j-pop", "modern-pop", "pop", "J-pop", ["idol pop"], ["japan"], null, null],
  ["k-pop", "modern-pop", "pop", "K-pop", [], ["korea"], null, null],
  ["c-pop", "modern-pop", "pop", "C-pop and Mandopop", ["Cantopop", "Mandopop", "Zhongguo Feng", "Hokkien Pop"], ["china"], null, null],
  ["vocaloid", "modern-pop", "pop", "Vocaloid", [], ["japan"], 2007, null],
  ["v-pop", "modern-pop", "pop", "Southeast Asian pop", ["opm", "thai pop", "P-pop", "Indo-Pop", "Manila Sound"], ["southeast-asia"], null, null],
  ["russian-pop", "modern-pop", "pop", "Russian and Slavic pop", ["estrada"], ["russia"], null, null],
  ["turkish-pop", "modern-pop", "pop", "Turkish pop", [], ["turkey"], null, null],
  ["arabic-pop", "modern-pop", "pop", "Arabic pop", ["khaleeji pop"], ["mena"], null, null],
  ["persian-pop", "modern-pop", "pop", "Persian pop", ["los angeles persian"], ["iran"], null, null],
  ["indian-pop", "modern-pop", "pop", "Indipop", [], ["india"], null, null],
  ["nordic-pop", "modern-pop", "pop", "Nordic and dansband pop", ["Dansband", "swedish pop"], ["scandinavia"], null, null],
  ["old-school-hip-hop", "old-school", "pop", "Old school hip hop", ["Pop Rap", "electro rap", "Beatbox"], [], 1979, 1985],
  ["golden-age", "old-school", "pop", "Golden age boom bap", ["Boom Bap", "Conscious"], [], 1986, 1996],
  ["miami-bass", "old-school", "pop", "Miami bass", ["booty bass"], ["florida"], 1985, null],
  ["toasting", "old-school", "pop", "Toasting and MC chant", [], ["jamaica"], 1960, null],
  ["g-funk", "regional-rap", "pop", "G-funk and West Coast", ["gangsta", "west coast rap", "Thug Rap"], [], 1992, null],
  ["east-coast-hardcore", "regional-rap", "pop", "East Coast hardcore", ["Hardcore Hip-Hop", "mafioso"], [], 1993, null],
  ["horrorcore", "regional-rap", "pop", "Horrorcore", [], [], 1994, null],
  ["southern-rap", "regional-rap", "pop", "Southern rap and dirty south", ["dirty south", "chopped and screwed", "Screw"], [], 1995, null],
  ["bounce", "regional-rap", "pop", "New Orleans bounce", [], ["new-orleans"], 1989, null],
  ["crunk", "regional-rap", "pop", "Crunk and snap", ["Snap"], [], 1997, 2008],
  ["hyphy", "regional-rap", "pop", "Hyphy", [], ["bay-area"], 2000, null],
  ["jerk", "regional-rap", "pop", "Jerk and ratchet", ["ratchet"], [], 2008, null],
  ["memphis-rap", "regional-rap", "pop", "Memphis rap", ["memphis phonk", "tape rap"], ["memphis"], 1990, null],
  ["phonk", "regional-rap", "pop", "Phonk", ["drift phonk"], [], 2016, null],
  ["trap", "modern-rap", "pop", "Trap", [], [], 2003, null],
  ["drill", "modern-rap", "pop", "Drill", ["uk drill", "brooklyn drill"], [], 2011, null],
  ["cloud-rap", "modern-rap", "pop", "Cloud rap", ["emo rap"], [], 2009, null],
  ["rage", "modern-rap", "pop", "Rage and plugg", ["plugg", "pluggnb"], [], 2018, null],
  ["abstract-hip-hop", "modern-rap", "pop", "Abstract and instrumental hip hop", ["Instrumental", "Low Bap"], [], 1994, null],
  ["jazz-rap", "modern-rap", "pop", "Jazz rap", ["Jazzy Hip-Hop"], [], 1988, null],
  ["lofi-hip-hop", "modern-rap", "pop", "Lo-fi hip hop", ["lofi beats", "chillhop"], [], 2013, null],
  ["experimental-hip-hop", "modern-rap", "pop", "Experimental hip hop", ["Industrial Hip-Hop"], [], 1999, null],
  ["grime", "modern-rap", "pop", "Grime", [], ["uk"], 2002, null],
  ["uk-hip-hop", "modern-rap", "pop", "UK hip hop", ["britcore", "uk rap"], ["uk"], null, null],
  ["french-rap", "modern-rap", "pop", "French rap and Francophone", ["rap francais"], ["france"], null, null],
  ["latin-trap", "modern-rap", "pop", "Latin trap", [], [], 2015, null],
  ["afro-trap", "modern-rap", "pop", "Afrotrap", [], [], 2015, null],
  ["rap-rock", "modern-rap", "pop", "Rap rock and rapcore", ["rapcore"], [], 1986, null],
  ["turntablism", "modern-rap", "pop", "Turntablism", ["Cut-up/DJ", "DJ Battle Tool"], [], 1985, null],
  ["religious-rap", "modern-rap", "pop", "Christian rap", ["christian hip hop"], [], 1985, null],
  ["disco", "disco-family", "electronic", "Disco", ["philly disco"], [], 1974, 1982],
  ["euro-disco", "disco-family", "electronic", "Euro-disco", ["munich disco"], [], 1975, 1985],
  ["italo-disco", "disco-family", "electronic", "Italo-disco", [], ["italy"], 1980, 1990],
  ["hi-nrg", "disco-family", "electronic", "Hi-NRG", [], [], 1980, null],
  ["space-disco", "disco-family", "electronic", "Space disco", ["cosmic disco"], [], 1977, 1985],
  ["nu-disco", "disco-family", "electronic", "Nu-disco", ["disco edits"], [], 2005, null],
  ["disco-polo", "disco-family", "electronic", "Disco polo", [], ["poland"], 1990, null],
  ["freestyle", "disco-family", "electronic", "Latin freestyle", [], [], 1983, 1995],
  ["eurobeat", "disco-family", "electronic", "Eurobeat", ["parapara"], [], 1985, null],
  ["eurodance", "disco-family", "electronic", "Eurodance", ["Italodance", "Hands Up"], [], 1990, null],
  ["electro-swing", "disco-family", "electronic", "Electro swing", [], [], 2005, null],
  ["chicago-house", "house", "electronic", "Chicago house", ["jack", "jackin house"], ["chicago"], 1984, null],
  ["acid-house", "house", "electronic", "Acid house", ["Acid"], [], 1986, null],
  ["deep-house", "house", "electronic", "Deep house", [], [], 1986, null],
  ["garage-house", "house", "electronic", "Garage house", ["new jersey garage", "Ballroom"], [], 1985, null],
  ["hip-house", "house", "electronic", "Hip house", [], [], 1987, null],
  ["italo-house", "house", "electronic", "Italo house", ["piano house"], [], 1988, null],
  ["euro-house", "house", "electronic", "Euro house", [], [], 1990, null],
  ["progressive-house", "house", "electronic", "Progressive house", [], [], 1992, null],
  ["tribal-house", "house", "electronic", "Tribal house", ["Tribal"], [], 1993, null],
  ["french-house", "house", "electronic", "French house", ["filter house"], ["france"], 1995, null],
  ["tech-house", "house", "electronic", "Tech house", [], [], 1995, null],
  ["hard-house", "house", "electronic", "Hard house", ["nrg"], [], 1995, null],
  ["electro-house", "house", "electronic", "Electro and big room house", ["big room", "complextro"], [], 2005, null],
  ["minimal-house", "house", "electronic", "Microhouse", [], [], 1998, null],
  ["future-house", "house", "electronic", "Future and bass house", ["bass house"], [], 2013, null],
  ["tropical-house", "house", "electronic", "Tropical house", [], [], 2013, null],
  ["lofi-house", "house", "electronic", "Lo-fi and outsider house", ["outsider house"], [], 2014, null],
  ["ghetto-house", "house", "electronic", "Ghetto house", ["Ghetto"], ["chicago"], 1992, null],
  ["ambient-house", "house", "electronic", "Ambient house and Balearic", ["Balearic"], [], 1988, null],
  ["afro-house", "house", "electronic", "Afro house", ["afro tech"], [], 2005, null],
  ["amapiano", "house", "electronic", "Amapiano", ["log drum"], ["south-africa"], 2012, null],
  ["gqom", "house", "electronic", "Gqom", [], ["south-africa"], 2010, null],
  ["kwaito", "house", "electronic", "Kwaito", ["Spaza", "Motswako"], ["south-africa"], 1990, null],
  ["detroit-techno", "techno", "electronic", "Detroit techno", [], ["detroit"], 1985, null],
  ["minimal-techno", "techno", "electronic", "Minimal techno", ["Minimal"], [], 1993, null],
  ["dub-techno", "techno", "electronic", "Dub techno", ["Deep Techno"], [], 1993, null],
  ["hard-techno", "techno", "electronic", "Hard techno and schranz", ["Schranz", "Hard Beat"], [], 1995, null],
  ["acid-techno", "techno", "electronic", "Acid techno", [], [], 1993, null],
  ["industrial-techno", "techno", "electronic", "Industrial and warehouse techno", ["berlin techno"], [], 2010, null],
  ["bleep-techno", "techno", "electronic", "Bleep techno", ["Bleep", "bleep and bass"], ["uk"], 1989, 1992],
  ["new-beat", "techno", "electronic", "New beat", [], ["belgium"], 1987, 1990],
  ["ebm", "techno", "electronic", "EBM", ["electronic body music", "Dark Electro"], [], 1981, null],
  ["electroclash", "techno", "electronic", "Electroclash", [], [], 1999, 2005],
  ["electro", "techno", "electronic", "Electro", ["electro funk"], [], 1982, null],
  ["ghettotech", "techno", "electronic", "Ghettotech", ["Booty"], ["detroit"], 1994, null],
  ["skweee", "techno", "electronic", "Skweee", [], ["scandinavia"], 2005, null],
  ["makina", "techno", "electronic", "Makina", ["Hyper Techno"], ["spain"], 1991, null],
  ["bouncy-techno", "techno", "electronic", "Bouncy techno and scouse house", ["Donk", "scouse house"], ["uk"], 1995, null],
  ["trance", "trance-family", "electronic", "Classic and uplifting trance", ["uplifting trance", "Euro Trance", "Neo Trance"], [], 1990, null],
  ["progressive-trance", "trance-family", "electronic", "Progressive trance", [], [], 1996, null],
  ["tech-trance", "trance-family", "electronic", "Tech trance", [], [], 1999, null],
  ["hard-trance", "trance-family", "electronic", "Hard trance", [], [], 1995, null],
  ["goa-trance", "trance-family", "electronic", "Goa trance", [], ["india"], 1990, 1998],
  ["psytrance", "trance-family", "electronic", "Psytrance", ["Psy-Trance", "full on"], [], 1996, null],
  ["dark-psy", "trance-family", "electronic", "Dark psytrance and forest", ["darkpsy", "forest psy"], [], 2000, null],
  ["suomisaundi", "trance-family", "electronic", "Suomisaundi", [], ["finland"], 1997, null],
  ["psybient", "trance-family", "electronic", "Psybient and psydub", ["psychill", "psydub"], [], 1995, null],
  ["rave-hardcore", "hardcore-family", "electronic", "Breakbeat hardcore", ["uk hardcore", "rave"], ["uk"], 1990, 1994],
  ["happy-hardcore", "hardcore-family", "electronic", "Happy hardcore", [], [], 1993, null],
  ["gabber", "hardcore-family", "electronic", "Gabber", ["mainstream hardcore"], ["netherlands"], 1992, null],
  ["doomcore", "hardcore-family", "electronic", "Doomcore", [], [], 1993, null],
  ["speedcore", "hardcore-family", "electronic", "Speedcore and extratone", ["extratone", "splittercore"], [], 1995, null],
  ["hardstyle", "hardcore-family", "electronic", "Hardstyle", ["rawstyle"], [], 2000, null],
  ["jumpstyle", "hardcore-family", "electronic", "Jumpstyle", [], [], 1997, null],
  ["frenchcore", "hardcore-family", "electronic", "Frenchcore and uptempo", ["uptempo"], [], 2000, null],
  ["j-core", "hardcore-family", "electronic", "J-core", ["Nerdcore Techno"], ["japan"], 2000, null],
  ["lento-violento", "hardcore-family", "electronic", "Lento violento", [], ["italy"], 2000, null],
  ["freetekno", "hardcore-family", "electronic", "Freetekno", ["tekno"], [], 1995, null],
  ["breakbeat", "breakbeat-family", "pop", "Breakbeat", ["Breaks", "nu skool breaks", "Progressive Breaks"], [], 1990, null],
  ["big-beat", "breakbeat-family", "pop", "Big beat", [], [], 1994, 2001],
  ["jungle", "breakbeat-family", "pop", "Jungle", ["ragga jungle"], ["uk"], 1992, null],
  ["drum-and-bass", "breakbeat-family", "pop", "Drum and bass", ["Drum n Bass", "liquid funk", "neurofunk", "jump up"], [], 1994, null],
  ["halftime", "breakbeat-family", "pop", "Halftime", [], [], 2010, null],
  ["breakcore", "breakbeat-family", "pop", "Breakcore", [], [], 1995, null],
  ["uk-garage", "breakbeat-family", "pop", "UK garage", ["2-step", "Speed Garage"], ["uk"], 1994, null],
  ["bassline", "breakbeat-family", "pop", "Bassline", ["niche"], ["uk"], 2003, null],
  ["dubstep", "breakbeat-family", "pop", "Dubstep", [], ["uk"], 2002, null],
  ["brostep", "breakbeat-family", "pop", "Brostep and riddim", ["riddim"], [], 2009, null],
  ["future-bass", "breakbeat-family", "pop", "Future bass", [], [], 2012, null],
  ["future-garage", "breakbeat-family", "pop", "Future garage", [], [], 2008, null],
  ["uk-funky", "breakbeat-family", "pop", "UK funky", [], ["uk"], 2007, null],
  ["wonky", "breakbeat-family", "pop", "Wonky and glitch hop", ["Glitch Hop", "beat scene"], [], 2005, null],
  ["broken-beat", "breakbeat-family", "pop", "Broken beat", [], ["uk"], 1998, null],
  ["footwork", "breakbeat-family", "pop", "Footwork and juke", ["Juke"], ["chicago"], 2005, null],
  ["baltimore-club", "breakbeat-family", "pop", "Baltimore club", [], [], 1990, null],
  ["jersey-club", "breakbeat-family", "pop", "Jersey club", [], [], 2005, null],
  ["moombahton", "breakbeat-family", "pop", "Moombahton", [], [], 2009, null],
  ["deconstructed-club", "breakbeat-family", "pop", "Deconstructed club", [], [], 2014, null],
  ["bass-music", "breakbeat-family", "pop", "Bass music and trap EDM", ["festival trap"], [], 2010, null],
  ["beatdown", "breakbeat-family", "pop", "Beatdown", [], [], 2007, null],
  ["funkot", "breakbeat-family", "pop", "Funkot", [], ["indonesia"], 1998, null],
  ["singeli", "breakbeat-family", "pop", "Singeli", [], ["tanzania"], 2010, null],
  ["downtempo", "downtempo-family", "electronic", "Downtempo", ["chill out"], [], 1990, null],
  ["trip-hop", "downtempo-family", "electronic", "Trip hop", ["bristol sound"], ["uk"], 1991, null],
  ["illbient", "downtempo-family", "electronic", "Illbient", [], [], 1994, null],
  ["leftfield", "downtempo-family", "electronic", "Leftfield", [], [], 1990, null],
  ["chillwave", "downtempo-family", "electronic", "Chillwave", ["glo-fi", "Hypnagogic pop"], [], 2009, null],
  ["vaporwave", "downtempo-family", "electronic", "Vaporwave", ["mallsoft"], [], 2011, null],
  ["future-funk", "downtempo-family", "electronic", "Future funk", [], [], 2013, null],
  ["witch-house", "downtempo-family", "electronic", "Witch house", [], [], 2009, null],
  ["ambient", "ambient-family", "electronic", "Ambient", ["eno ambient"], [], 1975, null],
  ["dark-ambient", "ambient-family", "electronic", "Dark ambient", ["Ritual", "Occult"], [], 1985, null],
  ["space-ambient", "ambient-family", "electronic", "Space ambient", ["space music"], [], 1975, null],
  ["berlin-school", "ambient-family", "electronic", "Berlin school", [], ["germany"], 1972, null],
  ["new-age", "ambient-family", "electronic", "New age", [], [], 1975, null],
  ["dungeon-synth", "ambient-family", "electronic", "Dungeon synth", ["Comfy Synth"], [], 1990, null],
  ["ambient-techno", "ambient-family", "electronic", "Ambient techno", [], [], 1990, null],
  ["japanese-ambient", "ambient-family", "electronic", "Kankyo ongaku", ["environmental music"], ["japan"], 1980, null],
  ["idm", "idm-family", "electronic", "IDM", ["braindance"], [], 1992, null],
  ["glitch", "idm-family", "electronic", "Glitch electronica", ["clicks n cuts", "glitchtronica"], [], 1994, null],
  ["folktronica", "idm-family", "electronic", "Folktronica", ["Indietronica"], [], 2000, null],
  ["electronica", "idm-family", "electronic", "Electronica", [], [], 1995, null],
  ["industrial", "idm-family", "electronic", "Industrial", ["Rhythmic Noise", "power noise"], [], 1975, null],
  ["aggrotech", "idm-family", "electronic", "Aggrotech and dark electro", ["hellektro"], [], 1995, null],
  ["dark-wave", "idm-family", "electronic", "Darkwave", [], [], 1980, null],
  ["minimal-wave", "idm-family", "electronic", "Minimal synth", [], [], 1978, null],
  ["neofolk", "idm-family", "electronic", "Neofolk", ["martial industrial"], [], 1985, null],
  ["synthwave", "synthwave-family", "electronic", "Synthwave", ["outrun", "retrowave"], [], 2007, null],
  ["darksynth", "synthwave-family", "electronic", "Darksynth", [], [], 2012, null],
  ["chiptune", "synthwave-family", "electronic", "Chiptune", ["Bitpop", "8-bit"], [], 1985, null],
  ["future-pop", "synthwave-family", "electronic", "Future pop", [], [], 1997, null],
  ["mento", "jamaican", "americas", "Mento", [], ["jamaica"], 1940, 1960],
  ["ska", "jamaican", "americas", "Ska", ["two-tone", "ska punk", "third wave ska"], ["jamaica"], 1959, null],
  ["rocksteady", "jamaican", "americas", "Rocksteady", [], ["jamaica"], 1966, 1968],
  ["roots-reggae", "jamaican", "americas", "Roots reggae", ["Reggae", "one drop"], ["jamaica"], 1968, null],
  ["lovers-rock", "jamaican", "americas", "Lovers rock", [], ["uk"], 1975, null],
  ["dub", "jamaican", "americas", "Dub", ["Dub Poetry", "steppers"], ["jamaica"], 1968, null],
  ["early-dancehall", "jamaican", "americas", "Early dancehall", ["Dancehall"], ["jamaica"], 1979, 1990],
  ["ragga", "jamaican", "americas", "Ragga and digital dancehall", ["Ragga HipHop", "riddim dancehall"], ["jamaica"], 1985, null],
  ["reggae-pop", "jamaican", "americas", "Reggae-pop and fusion", ["Reggae Gospel", "pop reggae"], [], 1980, null],
  ["nyabinghi", "jamaican", "americas", "Nyabinghi", ["rasta drumming"], ["jamaica"], null, null],
  ["kumina", "jamaican", "americas", "Kumina", [], ["jamaica"], null, null],
  ["calypso", "trinidad", "americas", "Calypso", ["kaiso"], ["trinidad"], null, null],
  ["soca", "trinidad", "americas", "Soca", ["power soca", "groovy soca"], ["trinidad"], 1975, null],
  ["steelband", "trinidad", "americas", "Steelband", ["Steel Band", "pan"], ["trinidad"], null, null],
  ["rapso", "trinidad", "americas", "Rapso", [], ["trinidad"], null, null],
  ["chutney", "trinidad", "americas", "Chutney", ["chutney soca"], ["trinidad"], null, null],
  ["junkanoo", "trinidad", "americas", "Junkanoo", [], ["bahamas"], null, null],
  ["bouyon", "trinidad", "americas", "Bouyon", ["cadence-lypso"], ["dominica"], null, null],
  ["bubbling", "trinidad", "americas", "Bubbling", [], ["netherlands-antilles"], null, null],
  ["zouk", "french-caribbean", "americas", "Zouk", ["zouk love"], ["antilles"], 1980, null],
  ["kompa", "french-caribbean", "americas", "Kompa", ["Compas", "konpa", "cadence"], ["haiti"], null, null],
  ["rara", "french-caribbean", "americas", "Rara", [], ["haiti"], null, null],
  ["twoubadou", "french-caribbean", "americas", "Twoubadou", ["haitian troubadour"], ["haiti"], null, null],
  ["gwo-ka", "french-caribbean", "americas", "Gwo ka", [], ["guadeloupe"], null, null],
  ["bele", "french-caribbean", "americas", "Bele and chouval bwa", ["chouval bwa"], ["martinique"], null, null],
  ["beguine", "french-caribbean", "americas", "Biguine", [], ["martinique"], null, null],
  ["kaseko", "french-caribbean", "americas", "Kaseko", [], ["suriname"], null, null],
  ["punta", "french-caribbean", "americas", "Punta and paranda", ["paranda", "garifuna"], ["belize", "honduras"], null, null],
  ["son-cubano", "cuban", "americas", "Son cubano", ["Son", "Cubano", "Sonero", "Son Montuno"], ["cuba"], null, null],
  ["danzon", "cuban", "americas", "Danzon", ["contradanza", "habanera"], ["cuba"], null, null],
  ["bolero", "cuban", "americas", "Bolero", ["filin"], ["cuba"], null, null],
  ["rumba-cubana", "cuban", "americas", "Rumba (guaguanco, yambu, columbia)", ["Rumba", "Guaguancó", "yambu", "columbia"], ["cuba"], null, null],
  ["mambo", "cuban", "americas", "Mambo", [], ["cuba"], 1938, 1960],
  ["cha-cha", "cuban", "americas", "Cha-cha-cha", [], ["cuba"], 1953, null],
  ["charanga", "cuban", "americas", "Charanga and pachanga", ["Pachanga"], ["cuba"], null, null],
  ["guajira", "cuban", "americas", "Guajira and punto", ["punto guajiro", "Guaracha"], ["cuba"], null, null],
  ["descarga", "cuban", "americas", "Descarga", [], ["cuba"], null, null],
  ["timba", "cuban", "americas", "Timba", [], ["cuba"], 1989, null],
  ["nueva-trova", "cuban", "americas", "Trova and nueva trova", ["Trova"], ["cuba"], null, null],
  ["santeria", "cuban", "americas", "Bata and santeria", ["Afro-Cuban", "bata", "lucumi", "Yoruba"], ["cuba"], null, null],
  ["changui", "cuban", "americas", "Changui", [], ["cuba"], null, null],
  ["salsa", "puerto-rico-dr", "americas", "Salsa", ["salsa dura", "salsa romantica"], [], 1965, null],
  ["boogaloo", "puerto-rico-dr", "americas", "Latin boogaloo", [], [], 1965, 1970],
  ["plena", "puerto-rico-dr", "americas", "Plena", [], ["puerto-rico"], null, null],
  ["bomba", "puerto-rico-dr", "americas", "Bomba", [], ["puerto-rico"], null, null],
  ["jibaro", "puerto-rico-dr", "americas", "Jibaro and aguinaldo", ["Aguinaldo", "Cuatro"], ["puerto-rico"], null, null],
  ["reggaeton", "puerto-rico-dr", "americas", "Reggaeton", ["dembow", "perreo"], [], 1995, null],
  ["merengue", "puerto-rico-dr", "americas", "Merengue", ["merengue tipico"], ["dominican-republic"], null, null],
  ["bachata", "puerto-rico-dr", "americas", "Bachata", [], ["dominican-republic"], null, null],
  ["mariachi", "mexican", "americas", "Mariachi and son jalisciense", ["son jalisciense"], ["mexico"], null, null],
  ["ranchera", "mexican", "americas", "Ranchera", [], ["mexico"], null, null],
  ["son-jarocho", "mexican", "americas", "Son jarocho", ["huapango"], ["mexico"], null, null],
  ["norteno", "mexican", "americas", "Norteno and conjunto", ["Norteño", "Conjunto"], ["mexico", "texas"], null, null],
  ["corrido", "mexican", "americas", "Corrido and corridos tumbados", ["corridos tumbados"], ["mexico"], null, null],
  ["banda", "mexican", "americas", "Banda sinaloense", ["Duranguense"], ["mexico"], null, null],
  ["tejano", "mexican", "americas", "Tejano", [], ["texas"], null, null],
  ["marimba-orquesta", "mexican", "americas", "Marimba orquesta", ["Marimba", "chapin marimba"], ["guatemala", "mexico"], null, null],
  ["cumbia", "colombia-venezuela", "americas", "Cumbia", ["cumbia villera", "chicha", "cumbia sonidera"], ["colombia"], null, null],
  ["vallenato", "colombia-venezuela", "americas", "Vallenato", [], ["colombia"], null, null],
  ["porro", "colombia-venezuela", "americas", "Porro and gaita", ["Gaita", "gaita zuliana"], ["colombia"], null, null],
  ["champeta", "colombia-venezuela", "americas", "Champeta", [], ["colombia"], null, null],
  ["currulao", "colombia-venezuela", "americas", "Currulao and Pacific marimba", ["Bultrón"], ["colombia"], null, null],
  ["bambuco", "colombia-venezuela", "americas", "Bambuco and pasillo", ["pasillo"], ["colombia", "ecuador"], null, null],
  ["joropo", "colombia-venezuela", "americas", "Joropo", ["llanera"], ["venezuela", "colombia"], null, null],
  ["huayno", "andean", "americas", "Huayno", ["Quechua", "Kaskawi"], ["peru", "bolivia"], null, null],
  ["andean-folk", "andean", "americas", "Andean folk ensemble", ["Andean Music", "sikuri", "zampona"], ["andes"], null, null],
  ["musica-criolla", "andean", "americas", "Musica criolla and vals peruano", ["Música Criolla", "vals peruano", "marinera"], ["peru"], null, null],
  ["afro-peruvian", "andean", "americas", "Afro-Peruvian", ["festejo", "lando"], ["peru"], null, null],
  ["saya", "andean", "americas", "Saya and caporales", ["caporales", "morenada"], ["bolivia"], null, null],
  ["tango", "southern-cone", "americas", "Tango", ["tango argentino"], ["argentina", "uruguay"], null, null],
  ["milonga", "southern-cone", "americas", "Milonga", [], ["argentina", "uruguay"], null, null],
  ["nuevo-tango", "southern-cone", "americas", "Nuevo tango", ["piazzolla", "tango nuevo"], ["argentina"], 1955, null],
  ["electrotango", "southern-cone", "americas", "Electrotango", ["electro tango"], [], 2000, null],
  ["chacarera", "southern-cone", "americas", "Chacarera and zamba", ["Zamba"], ["argentina"], null, null],
  ["chamame", "southern-cone", "americas", "Chamame", ["Chamamé"], ["argentina"], null, null],
  ["guarania", "southern-cone", "americas", "Guarania and polca paraguaya", ["polca paraguaya"], ["paraguay"], null, null],
  ["candombe", "southern-cone", "americas", "Candombe", [], ["uruguay"], null, null],
  ["murga", "southern-cone", "americas", "Murga", ["murga uruguaya"], ["uruguay"], null, null],
  ["cueca", "southern-cone", "americas", "Cueca and tonada", ["tonada"], ["chile"], null, null],
  ["nueva-cancion", "southern-cone", "americas", "Nueva cancion", ["canto nuevo"], [], 1960, null],
  ["samba", "brazil", "americas", "Samba", ["Samba-Canção", "Batucada", "partido alto", "Marcha Carnavalesca"], ["brazil"], null, null],
  ["pagode", "brazil", "americas", "Pagode", [], ["brazil"], null, null],
  ["choro", "brazil", "americas", "Choro", ["Seresta"], ["brazil"], null, null],
  ["bossa-nova", "brazil", "americas", "Bossa nova", ["Bossanova"], ["brazil"], 1958, null],
  ["mpb", "brazil", "americas", "MPB", ["musica popular brasileira"], ["brazil"], 1965, null],
  ["tropicalia", "brazil", "americas", "Tropicalia", [], ["brazil"], 1967, 1972],
  ["forro", "brazil", "americas", "Forro and baiao", ["Forró", "Baião", "xote"], ["brazil"], null, null],
  ["frevo", "brazil", "americas", "Frevo and maracatu", ["maracatu"], ["brazil"], null, null],
  ["axe", "brazil", "americas", "Axe and samba-reggae", ["Axé", "samba-reggae"], ["brazil"], null, null],
  ["carimbo", "brazil", "americas", "Carimbo and lambada", ["Carimbó", "Lambada"], ["brazil"], null, null],
  ["sertanejo", "brazil", "americas", "Sertanejo and caipira", ["Caipira", "moda de viola"], ["brazil"], null, null],
  ["brega", "brazil", "americas", "Brega and tecnobrega", ["tecnobrega"], ["brazil"], null, null],
  ["baile-funk", "brazil", "americas", "Baile funk", ["Favela Funk", "funk carioca", "funk mandelao"], ["brazil"], 1989, null],
  ["capoeira", "brazil", "americas", "Capoeira", ["berimbau"], ["brazil"], null, null],
  ["highlife", "west-africa", "africa-mena-southasia", "Highlife", ["guitar band highlife"], ["ghana", "nigeria"], null, null],
  ["hiplife", "west-africa", "africa-mena-southasia", "Hiplife and azonto", ["Azonto"], ["ghana"], 1990, null],
  ["afrobeat", "west-africa", "africa-mena-southasia", "Afrobeat", ["fela"], ["nigeria"], 1970, null],
  ["afrobeats", "west-africa", "africa-mena-southasia", "Afrobeats", ["afropop", "afro-fusion"], ["nigeria", "ghana"], 2008, null],
  ["juju", "west-africa", "africa-mena-southasia", "Juju", [], ["nigeria"], null, null],
  ["fuji", "west-africa", "africa-mena-southasia", "Fuji and apala", ["apala", "sakara"], ["nigeria"], null, null],
  ["griot", "west-africa", "africa-mena-southasia", "Griot and kora tradition", ["jali", "kora"], ["mali", "senegal", "gambia"], null, null],
  ["mande-pop", "west-africa", "africa-mena-southasia", "Mande and wassoulou", ["wassoulou", "manding swing"], ["mali", "guinea"], null, null],
  ["desert-blues", "west-africa", "africa-mena-southasia", "Desert blues", ["tishoumaren", "assouf"], ["sahel"], 1980, null],
  ["mbalax", "west-africa", "africa-mena-southasia", "Mbalax", ["sabar"], ["senegal"], null, null],
  ["morna", "west-africa", "africa-mena-southasia", "Morna and coladeira", ["coladeira"], ["cape-verde"], null, null],
  ["funana", "west-africa", "africa-mena-southasia", "Funana and batuque", ["Funaná", "batuque"], ["cape-verde"], null, null],
  ["west-african-drum", "west-africa", "africa-mena-southasia", "Djembe ensemble", ["djembe", "dundun", "mandingue drumming"], ["guinea", "mali"], null, null],
  ["ewe-drumming", "west-africa", "africa-mena-southasia", "Ewe dance drumming", ["agbekor", "gahu", "ewe"], ["ghana", "togo"], null, null],
  ["soukous", "central-africa", "africa-mena-southasia", "Soukous and Congolese rumba", ["rumba congolaise", "ndombolo"], ["congo"], null, null],
  ["makossa", "central-africa", "africa-mena-southasia", "Makossa and bikutsi", ["bikutsi"], ["cameroon"], null, null],
  ["aka-polyphony", "central-africa", "africa-mena-southasia", "Central African forest polyphony", ["aka", "baka", "pygmy polyphony", "yodel polyphony"], ["central-africa"], null, null],
  ["benga", "east-africa", "africa-mena-southasia", "Benga", [], ["kenya"], null, null],
  ["taarab", "east-africa", "africa-mena-southasia", "Taarab", [], ["zanzibar", "kenya"], null, null],
  ["bongo-flava", "east-africa", "africa-mena-southasia", "Bongo flava", [], ["tanzania"], 1995, null],
  ["ethio-jazz", "east-africa", "africa-mena-southasia", "Ethio-jazz and Ethiopian pop", ["ethiopiques", "tizita"], ["ethiopia"], null, null],
  ["ethiopian-chant", "east-africa", "africa-mena-southasia", "Ethiopian orthodox zema", ["zema", "mezmur"], ["ethiopia"], null, null],
  ["somali", "east-africa", "africa-mena-southasia", "Somali music", ["qaraami"], ["somalia"], null, null],
  ["kidandali", "east-africa", "africa-mena-southasia", "Kidandali and Ugandan pop", [], ["uganda"], null, null],
  ["mbaqanga", "southern-africa", "africa-mena-southasia", "Mbaqanga and township jive", ["township jive"], ["south-africa"], null, null],
  ["isicathamiya", "southern-africa", "africa-mena-southasia", "Isicathamiya", ["mbube"], ["south-africa"], null, null],
  ["marabi", "southern-africa", "africa-mena-southasia", "Marabi and kwela", ["kwela"], ["south-africa"], null, null],
  ["cape-jazz", "southern-africa", "africa-mena-southasia", "Cape jazz", [], ["south-africa"], null, null],
  ["maskandi", "southern-africa", "africa-mena-southasia", "Maskandi", [], ["south-africa"], null, null],
  ["chimurenga", "southern-africa", "africa-mena-southasia", "Chimurenga and mbira music", ["mbira dzavadzimu"], ["zimbabwe"], null, null],
  ["kizomba", "southern-africa", "africa-mena-southasia", "Kizomba, semba and kuduro", ["semba", "kuduro"], ["angola"], null, null],
  ["marrabenta", "southern-africa", "africa-mena-southasia", "Marrabenta", [], ["mozambique"], null, null],
  ["malagasy", "southern-africa", "africa-mena-southasia", "Malagasy salegy and tsapiky", ["Salegy", "tsapiky", "valiha"], ["madagascar"], null, null],
  ["sega", "southern-africa", "africa-mena-southasia", "Sega and maloya", ["Séga", "Maloya"], ["mauritius", "reunion"], null, null],
  ["arabic-classical", "arabic-maqam", "africa-mena-southasia", "Arabic classical and tarab", ["tarab", "Klasik", "wasla", "takht"], ["egypt", "levant"], null, null],
  ["muwashshah", "arabic-maqam", "africa-mena-southasia", "Muwashshah and Andalusian nuba", ["Andalusian Classical", "nuba", "malouf"], ["maghreb"], null, null],
  ["iraqi-maqam", "arabic-maqam", "africa-mena-southasia", "Iraqi maqam", ["al-maqam al-iraqi", "chalghi"], ["iraq"], null, null],
  ["khaleeji", "arabic-maqam", "africa-mena-southasia", "Khaleeji", ["sawt", "liwa", "Khaliji"], ["gulf"], null, null],
  ["quranic-recitation", "arabic-maqam", "africa-mena-southasia", "Tajwid and religious chant", ["tajwid", "Adhan", "nasheed", "sufi inshad"], ["mena"], null, null],
  ["shaabi", "arabic-maqam", "africa-mena-southasia", "Shaabi and mahraganat", ["mahraganat", "electro shaabi"], ["egypt"], null, null],
  ["dabke", "arabic-maqam", "africa-mena-southasia", "Dabke", [], ["levant"], null, null],
  ["rai", "arabic-maqam", "africa-mena-southasia", "Rai", ["Raï"], ["algeria"], null, null],
  ["chaabi-maghreb", "arabic-maqam", "africa-mena-southasia", "Algerian and Moroccan chaabi", ["chaabi", "malhun"], ["maghreb"], null, null],
  ["gnawa", "arabic-maqam", "africa-mena-southasia", "Gnawa", ["lila"], ["morocco"], null, null],
  ["amazigh", "arabic-maqam", "africa-mena-southasia", "Amazigh music", ["berber", "ahidus", "ahwash"], ["maghreb"], null, null],
  ["yemenite", "arabic-maqam", "africa-mena-southasia", "Yemenite song", ["Yemenite Jewish", "sanaani"], ["yemen"], null, null],
  ["persian-classical", "persian-turkic", "africa-mena-southasia", "Persian classical (radif and dastgah)", ["radif", "dastgah", "avaz"], ["iran"], null, null],
  ["ottoman-classical", "persian-turkic", "africa-mena-southasia", "Ottoman classical and makam", ["turkish makam", "fasil", "mehter"], ["turkey"], null, null],
  ["sufi-ney", "persian-turkic", "africa-mena-southasia", "Mevlevi and Sufi ritual", ["sema", "mevlevi ayin", "zikr"], ["turkey", "iran"], null, null],
  ["turkish-folk", "persian-turkic", "africa-mena-southasia", "Turkish folk (turku, halay)", ["turku", "halay", "bozlak", "arabesk"], ["turkey"], null, null],
  ["mugham", "persian-turkic", "africa-mena-southasia", "Azerbaijani mugham", ["meykhana"], ["azerbaijan"], null, null],
  ["shashmaqam", "persian-turkic", "africa-mena-southasia", "Shashmaqam and Central Asian", ["bukharan"], ["uzbekistan", "tajikistan"], null, null],
  ["kurdish", "persian-turkic", "africa-mena-southasia", "Kurdish music", ["dengbej"], ["kurdistan"], null, null],
  ["armenian-folk", "persian-turkic", "africa-mena-southasia", "Armenian and Georgian", ["duduk", "georgian polyphony"], ["caucasus"], null, null],
  ["klezmer", "jewish", "africa-mena-southasia", "Klezmer", ["freylekhs", "doina"], ["eastern-europe"], null, null],
  ["cantorial", "jewish", "africa-mena-southasia", "Hazzanut", ["nusach"], ["diaspora"], null, null],
  ["sephardic", "jewish", "africa-mena-southasia", "Sephardic song", ["ladino"], ["mediterranean"], null, null],
  ["mizrahi", "jewish", "africa-mena-southasia", "Mizrahi and Zemer Ivri", ["Zemer Ivri", "israeli folk"], ["israel"], null, null],
  ["dhrupad", "hindustani", "africa-mena-southasia", "Dhrupad", ["dhamar"], ["north-india"], null, null],
  ["khayal", "hindustani", "africa-mena-southasia", "Khayal", ["bandish"], ["north-india"], null, null],
  ["hindustani-instrumental", "hindustani", "africa-mena-southasia", "Hindustani instrumental (gat)", ["sitar gat", "sarod", "jhala"], ["north-india"], null, null],
  ["thumri", "hindustani", "africa-mena-southasia", "Thumri and light classical", ["dadra", "tappa"], ["north-india"], null, null],
  ["ghazal", "hindustani", "africa-mena-southasia", "Ghazal", [], ["north-india", "pakistan"], null, null],
  ["qawwali", "hindustani", "africa-mena-southasia", "Qawwali", [], ["pakistan", "north-india"], null, null],
  ["bhajan", "hindustani", "africa-mena-southasia", "Bhajan and kirtan", ["kirtan", "Geet", "devotional"], ["india"], null, null],
  ["kriti", "carnatic", "africa-mena-southasia", "Kriti", ["varnam"], ["south-india"], null, null],
  ["carnatic-instrumental", "carnatic", "africa-mena-southasia", "Carnatic instrumental and RTP", ["ragam tanam pallavi", "veena", "mridangam"], ["south-india"], null, null],
  ["thillana", "carnatic", "africa-mena-southasia", "Thillana and Bharatanatyam", ["bharatanatyam"], ["south-india"], null, null],
  ["filmi", "south-asian-popular", "africa-mena-southasia", "Filmi and Bollywood", ["Bollywood", "Tamil Film Music", "Ryūkōka"], ["india"], null, null],
  ["bhangra", "south-asian-popular", "africa-mena-southasia", "Bhangra", ["dhol"], ["punjab"], null, null],
  ["baul", "south-asian-popular", "africa-mena-southasia", "Baul and Bengali folk", ["Bengali Music", "Bangladeshi Classical", "rabindra sangeet"], ["bengal"], null, null],
  ["lavani", "south-asian-popular", "africa-mena-southasia", "Lavani and Marathi folk", [], ["maharashtra"], null, null],
  ["rajasthani-folk", "south-asian-popular", "africa-mena-southasia", "Rajasthani folk", ["manganiyar", "langa"], ["rajasthan"], null, null],
  ["sufi-kafi", "south-asian-popular", "africa-mena-southasia", "Sufi kafi", ["kafi"], ["punjab", "sindh"], null, null],
  ["sri-lankan", "south-asian-popular", "africa-mena-southasia", "Sri Lankan baila and drums", ["Baila", "kandyan"], ["sri-lanka"], null, null],
  ["nepali-folk", "south-asian-popular", "africa-mena-southasia", "Nepali and Himalayan folk", ["lok dohori"], ["nepal"], null, null],
  ["tibetan", "south-asian-popular", "africa-mena-southasia", "Tibetan Buddhist chant", ["tibetan chant", "dungchen"], ["tibet"], null, null],
  ["asian-underground", "south-asian-popular", "africa-mena-southasia", "Asian Underground", ["Ethno-pop"], ["uk"], 1995, null],
  ["irish-trad", "celtic-british", "europe-asia-pacific", "Irish traditional dance music", ["reel", "jig", "session"], ["ireland"], null, null],
  ["sean-nos", "celtic-british", "europe-asia-pacific", "Sean-nos song", ["Sean-nós"], ["ireland"], null, null],
  ["scottish-trad", "celtic-british", "europe-asia-pacific", "Scottish traditional", ["strathspey", "scottish fiddle", "Mouth Music", "puirt a beul"], ["scotland"], null, null],
  ["piobaireachd", "celtic-british", "europe-asia-pacific", "Piobaireachd", ["ceol mor"], ["scotland"], null, null],
  ["english-folk", "celtic-british", "europe-asia-pacific", "English folk and morris", ["morris", "ceilidh", "Music Hall"], ["england"], null, null],
  ["welsh", "celtic-british", "europe-asia-pacific", "Welsh and Cornish", ["cerdd dant", "welsh harp"], ["wales"], null, null],
  ["breton", "celtic-british", "europe-asia-pacific", "Breton music", ["kan ha diskan", "fest-noz"], ["brittany"], null, null],
  ["galician", "celtic-british", "europe-asia-pacific", "Galician and Asturian", ["Galician Traditional", "muineira", "gaita galega"], ["galicia"], null, null],
  ["celtic-fusion", "celtic-british", "europe-asia-pacific", "Celtic fusion", ["celtic rock", "celtic new age"], [], 1970, null],
  ["nordic-fiddle", "nordic-baltic", "europe-asia-pacific", "Nordic fiddle and polska", ["Nordic", "polska", "hardingfele", "Népzene nordic"], ["scandinavia"], null, null],
  ["kulning", "nordic-baltic", "europe-asia-pacific", "Kulning and herding song", [], ["sweden", "norway"], null, null],
  ["joik", "nordic-baltic", "europe-asia-pacific", "Sami joik", ["Sámi Music"], ["sapmi"], null, null],
  ["rune-singing", "nordic-baltic", "europe-asia-pacific", "Runo song", ["runolaulu"], ["finland", "estonia"], null, null],
  ["baltic-folk", "nordic-baltic", "europe-asia-pacific", "Baltic folk (dainas, sutartines)", ["sutartines", "dainas", "kankles"], ["baltics"], null, null],
  ["nordic-folk-revival", "nordic-baltic", "europe-asia-pacific", "Nordic folk revival and ambient folk", ["nordic folk", "viking folk", "Neopagan"], [], 1990, null],
  ["volksmusik", "west-europe", "europe-asia-pacific", "Volksmusik and Alpine", ["yodel", "landler", "Schuhplattler"], ["alps"], null, null],
  ["polka", "west-europe", "europe-asia-pacific", "Polka", ["oberkrainer"], ["central-europe"], null, null],
  ["waltz-folk", "west-europe", "europe-asia-pacific", "Viennese and folk waltz", ["waltz", "landler waltz", "Liscio"], ["austria", "italy"], null, null],
  ["levenslied", "west-europe", "europe-asia-pacific", "Levenslied", ["smartlap"], ["netherlands"], null, null],
  ["basque", "west-europe", "europe-asia-pacific", "Basque music", ["trikitixa", "txalaparta"], ["basque"], null, null],
  ["occitan", "west-europe", "europe-asia-pacific", "Occitan music", [], ["occitania"], null, null],
  ["italian-folk", "west-europe", "europe-asia-pacific", "Italian folk (tarantella, canto a tenore)", ["tarantella", "canto a tenore", "Trallalero", "Canzone Napoletana"], ["italy"], null, null],
  ["maltese", "west-europe", "europe-asia-pacific", "Maltese ghana", ["Għana"], ["malta"], null, null],
  ["flamenco", "iberia", "europe-asia-pacific", "Flamenco", ["cante jondo", "bulerias", "solea"], ["andalusia"], null, null],
  ["rumba-flamenca", "iberia", "europe-asia-pacific", "Rumba flamenca and nuevo flamenco", ["rumba catalana", "nuevo flamenco"], ["spain"], null, null],
  ["copla", "iberia", "europe-asia-pacific", "Copla and pasodoble", ["Pasodoble", "cuple"], ["spain"], null, null],
  ["jota", "iberia", "europe-asia-pacific", "Jota", [], ["aragon"], null, null],
  ["catalan", "iberia", "europe-asia-pacific", "Catalan and sardana", ["Catalan Music", "Cobla", "sardana"], ["catalonia"], null, null],
  ["fado", "iberia", "europe-asia-pacific", "Fado", [], ["portugal"], null, null],
  ["hungarian-folk", "central-east-europe", "europe-asia-pacific", "Hungarian folk and verbunkos", ["Népzene", "tanchaz", "verbunkos", "csardas"], ["hungary"], null, null],
  ["romani", "central-east-europe", "europe-asia-pacific", "Romani music", ["gypsy", "lautari", "manele"], ["balkans"], null, null],
  ["polish-folk", "central-east-europe", "europe-asia-pacific", "Polish folk (mazurka, oberek, goral)", ["mazurka", "oberek", "goral"], ["poland"], null, null],
  ["czech-slovak", "central-east-europe", "europe-asia-pacific", "Czech and Slovak folk", ["dechovka", "fujara"], ["czechia", "slovakia"], null, null],
  ["russian-folk", "central-east-europe", "europe-asia-pacific", "Russian folk", ["balalaika", "chastushka", "khorovod"], ["russia"], null, null],
  ["ukrainian-folk", "central-east-europe", "europe-asia-pacific", "Ukrainian folk", ["kobzar", "bandura", "hopak"], ["ukraine"], null, null],
  ["estrada-romance", "central-east-europe", "europe-asia-pacific", "Russian romance and bard song", ["bard song", "avtorskaya pesnya", "russian romance"], ["russia"], null, null],
  ["balkan-brass", "balkans-mediterranean", "europe-asia-pacific", "Balkan brass", ["truba", "Kolo"], ["serbia"], null, null],
  ["bulgarian-folk", "balkans-mediterranean", "europe-asia-pacific", "Bulgarian folk and asymmetric dances", ["bulgarian voices", "horo", "ruchenitsa", "wedding music"], ["bulgaria"], null, null],
  ["macedonian-folk", "balkans-mediterranean", "europe-asia-pacific", "Macedonian and Greek aksak dance", ["macedonian", "kalamatianos", "cocek"], ["macedonia", "greece"], null, null],
  ["rebetiko", "balkans-mediterranean", "europe-asia-pacific", "Rebetiko", [], ["greece"], null, null],
  ["laiko", "balkans-mediterranean", "europe-asia-pacific", "Laiko and entekhno", ["Laïkó", "Éntekhno", "Néo Kyma"], ["greece"], null, null],
  ["cretan", "balkans-mediterranean", "europe-asia-pacific", "Cretan and nisiotika", ["nisiotika", "lyra"], ["greece"], null, null],
  ["tamburica", "balkans-mediterranean", "europe-asia-pacific", "Tamburica and Croatian folk", ["Tamburitza", "klapa", "Bećarac"], ["croatia"], null, null],
  ["turbo-folk", "balkans-mediterranean", "europe-asia-pacific", "Turbo-folk and pop-folk", ["chalga", "manele pop"], ["balkans"], 1985, null],
  ["albanian-iso", "balkans-mediterranean", "europe-asia-pacific", "Albanian iso-polyphony", ["iso-polyphony", "lab polyphony"], ["albania"], null, null],
  ["sevdalinka", "balkans-mediterranean", "europe-asia-pacific", "Sevdalinka", ["sevdah"], ["bosnia"], null, null],
  ["dinaric-rural", "balkans-mediterranean", "europe-asia-pacific", "Dinaric rural song (ganga, ojkanje, izvorna)", ["Ojkača", "Izvorna", "ganga", "ojkanje"], ["bosnia", "croatia"], null, null],
  ["gusle-epic", "balkans-mediterranean", "europe-asia-pacific", "South Slavic epic song with gusle", ["Gusle", "guslar", "epic decasyllable"], ["montenegro", "serbia", "bosnia"], null, null],
  ["guqin", "china", "europe-asia-pacific", "Guqin music", ["qin"], ["china"], null, null],
  ["chinese-classical", "china", "europe-asia-pacific", "Chinese classical (silk and bamboo)", ["sizhu", "jiangnan sizhu", "guzheng"], ["china"], null, null],
  ["chinese-opera", "china", "europe-asia-pacific", "Chinese opera (jingju, kunqu, yueju)", ["Peking opera", "kunqu", "cantonese opera"], ["china"], null, null],
  ["chinese-folk", "china", "europe-asia-pacific", "Chinese folk song and minority", ["shan'ge", "xintianyou"], ["china"], null, null],
  ["cantonese-music", "china", "europe-asia-pacific", "Cantonese music", ["guangdong yinyue"], ["guangdong"], null, null],
  ["nanguan", "china", "europe-asia-pacific", "Nanguan and Taiwanese", ["beiguan"], ["fujian", "taiwan"], null, null],
  ["chinese-orchestra", "china", "europe-asia-pacific", "Modern Chinese orchestra", ["guoyue", "minyue"], ["china"], 1920, null],
  ["gagaku", "japan", "europe-asia-pacific", "Gagaku", ["togaku", "komagaku"], ["japan"], null, null],
  ["shomyo", "japan", "europe-asia-pacific", "Shomyo", [], ["japan"], null, null],
  ["sankyoku", "japan", "europe-asia-pacific", "Sankyoku and sokyoku", ["Sokyoku", "koto music", "jiuta"], ["japan"], null, null],
  ["honkyoku", "japan", "europe-asia-pacific", "Honkyoku and shakuhachi", ["Shinkyoku", "komuso"], ["japan"], null, null],
  ["noh", "japan", "europe-asia-pacific", "Noh and kabuki music", ["nohgaku", "Nagauta", "kabuki", "Rōkyoku", "joruri"], ["japan"], null, null],
  ["minyo", "japan", "europe-asia-pacific", "Min'yo", ["Min'yō", "ondo"], ["japan"], null, null],
  ["taiko", "japan", "europe-asia-pacific", "Kumi-daiko", [], ["japan"], 1951, null],
  ["okinawan", "japan", "europe-asia-pacific", "Okinawan and Ryukyu", ["shima-uta", "sanshin"], ["okinawa"], null, null],
  ["korean-court", "korea", "europe-asia-pacific", "Korean court music", ["aak", "jeongak"], ["korea"], null, null],
  ["pansori", "korea", "europe-asia-pacific", "Pansori and sanjo", ["sanjo"], ["korea"], null, null],
  ["pungmul", "korea", "europe-asia-pacific", "Pungmul and samul nori", ["samul nori", "nongak"], ["korea"], null, null],
  ["mongolian", "central-north-asia", "europe-asia-pacific", "Mongolian (urtiin duu, khoomei)", ["Overtone Singing", "urtiin duu", "morin khuur"], ["mongolia"], null, null],
  ["tuvan", "central-north-asia", "europe-asia-pacific", "Tuvan throat singing", ["khoomei", "sygyt", "kargyraa"], ["tuva"], null, null],
  ["kazakh-kyrgyz", "central-north-asia", "europe-asia-pacific", "Kazakh and Kyrgyz", ["kuy", "dombra", "komuz"], ["central-asia"], null, null],
  ["javanese-gamelan", "southeast-asia", "europe-asia-pacific", "Javanese gamelan", ["Gamelan", "karawitan"], ["java"], null, null],
  ["balinese-gamelan", "southeast-asia", "europe-asia-pacific", "Balinese gamelan", ["gong kebyar", "kecak", "beleganjur"], ["bali"], null, null],
  ["sundanese", "southeast-asia", "europe-asia-pacific", "Sundanese degung and jaipongan", ["degung", "jaipongan", "tembang sunda"], ["sunda"], null, null],
  ["dangdut", "southeast-asia", "europe-asia-pacific", "Dangdut", ["koplo"], ["indonesia"], null, null],
  ["keroncong", "southeast-asia", "europe-asia-pacific", "Kroncong", [], ["indonesia"], null, null],
  ["thai-classical", "southeast-asia", "europe-asia-pacific", "Thai classical (piphat)", ["piphat", "mahori"], ["thailand"], null, null],
  ["luk-thung", "southeast-asia", "europe-asia-pacific", "Luk thung and luk krung", ["Luk Krung", "Phleng Phuea Chiwit"], ["thailand"], null, null],
  ["mor-lam", "southeast-asia", "europe-asia-pacific", "Mor lam", ["Mo Lam", "Lao Music", "khaen"], ["laos", "isan"], null, null],
  ["khmer", "southeast-asia", "europe-asia-pacific", "Khmer classical and pinpeat", ["Cambodian Classical", "pinpeat"], ["cambodia"], null, null],
  ["vietnamese", "southeast-asia", "europe-asia-pacific", "Vietnamese traditional", ["ca tru", "nha nhac", "Nhạc Vàng", "cai luong"], ["vietnam"], null, null],
  ["philippine", "southeast-asia", "europe-asia-pacific", "Philippine kulintang and kundiman", ["Philippine Classical", "kulintang", "kundiman", "rondalla"], ["philippines"], null, null],
  ["burmese", "southeast-asia", "europe-asia-pacific", "Burmese saing waing", ["hsaing waing", "mahagita"], ["myanmar"], null, null],
  ["malay", "southeast-asia", "europe-asia-pacific", "Malay traditional", ["joget", "zapin", "ghazal melayu"], ["malaysia"], null, null],
  ["aboriginal", "oceania", "europe-asia-pacific", "Aboriginal Australian", ["didgeridoo", "clapsticks", "songlines"], ["australia"], null, null],
  ["maori", "oceania", "europe-asia-pacific", "Maori waiata and haka", ["Waiata", "haka", "kapa haka"], ["aotearoa"], null, null],
  ["hawaiian", "oceania", "europe-asia-pacific", "Hawaiian (slack key, hula)", ["slack key", "hula", "steel guitar"], ["hawaii"], null, null],
  ["polynesian", "oceania", "europe-asia-pacific", "Polynesian (Tahiti, Samoa, Tonga)", ["Pacific", "himene"], ["polynesia"], null, null],
  ["melanesian", "oceania", "europe-asia-pacific", "Melanesian and Papuan", ["string band png", "bamboo band", "kaneka"], ["melanesia"], null, null],
  ["island-reggae", "oceania", "europe-asia-pacific", "Island reggae and Pacific pop", ["jawaiian"], ["pacific"], 1980, null],
]);
